In [1]:
# 필요한 모듈, 라이브러리 import

In [2]:
import pandas as pd
import numpy as np

In [3]:
# df1 ~ 2015년도 데이터 프레임 정의

In [4]:
df1 = pd.read_excel('data/USMassShootings.xlsx')

In [5]:
# df2 ~ 2022년도 데이터 프레임 정의

In [6]:
df2 = pd.read_csv('data/Mother Jones - Mass Shootings Database, 1982 - 2022 - Sheet1.csv')

In [7]:
# df1 컬럼들을 소문자로 변경

In [8]:
df1.columns = [x.lower() for x in df1.columns]

In [9]:
# df2 에서 location을 기준으로 df2에 state생성

In [10]:
df2.insert(2, 'state', df2['location'].str.split(',').replace(' ', '').str.get(1))

In [11]:
#병합 전 case 컬럼값 차이가 있나 확인

In [12]:
set_df1_case=set([casestr for casestr in df1['case']])
set_df2_case=set([casestr for casestr in df2['case']])
set_df1_case-set_df2_case

{'Newtown school shooting'}

In [13]:
df1[df1['case']=='Newtown school shooting']

,case,gender,shootingtype,race,location,state,date,year,summary,fatalities,...,priorsignsofmentalillness,mentalhealthnotes,weaponsobtainedlegally,whereweaponobtained,typeofweapons,numweapons,assault,weapondetails,latitude,longitude
9,Newtown school shooting,Male,Mass,White,"Newtown, Connecticut",Connecticut,12/14/2012,2012,"Adam Lanza, 20, shot his mother dead at their ...",28,...,Yes,Lanza had a history of serious mental health p...,No,Stolen from mother,"Two semiautomatic handguns, one rifle (assault...",4,Yes,"10mm Glock, 9mm SIG Sauer P226 semiautomatic h...",41.412323,-73.311424

In [14]:
df2[df2['date']=='12/14/2012']

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,weapon_details,race,gender,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year
73,Sandy Hook Elementary massacre,"Newtown, Connecticut",Connecticut,12/14/2012,"Adam Lanza, 20, shot his mother dead at their ...",27,2,29,School,20,...,"10mm Glock, 9mm SIG Sauer P226 semiautomatic h...",white,Male,http://usnews.nbcnews.com/_news/2012/12/14/159...,http://usnews.nbcnews.com/_news/2012/12/14/159...,http://usnews.nbcnews.com/_news/2012/12/14/159...,41.4123225,-73.31142358,Mass,2012

In [15]:
# df1 의 데이터 'Newtown school shooting' df2를 기준으로 통일

In [16]:
casename = [casestr for casestr in df2[df2['date']=='12/14/2012']['case']]

In [17]:
casename[0]

'Sandy Hook Elementary massacre'

In [18]:
#이름 적용

In [19]:
df1.loc[9,'case'] = casename[0]

In [20]:
df1[df1['case']==casename[0]]

,case,gender,shootingtype,race,location,state,date,year,summary,fatalities,...,priorsignsofmentalillness,mentalhealthnotes,weaponsobtainedlegally,whereweaponobtained,typeofweapons,numweapons,assault,weapondetails,latitude,longitude
9,Sandy Hook Elementary massacre,Male,Mass,White,"Newtown, Connecticut",Connecticut,12/14/2012,2012,"Adam Lanza, 20, shot his mother dead at their ...",28,...,Yes,Lanza had a history of serious mental health p...,No,Stolen from mother,"Two semiautomatic handguns, one rifle (assault...",4,Yes,"10mm Glock, 9mm SIG Sauer P226 semiautomatic h...",41.412323,-73.311424

In [21]:
# df1에서 필요없는 컬럼 제거

In [22]:
df1_1 = df1.drop(['gender', 'shootingtype', 'race', 'location', 'state', 'date',
       'year', 'summary', 'fatalities', 'wounded', 'totalvictims',
       'locationtype', 'priorsignsofmentalillness', 'mentalhealthnotes',
       'weaponsobtainedlegally', 'whereweaponobtained', 'typeofweapons'
         , 'weapondetails', 'latitude', 'longitude'], axis=1)

In [23]:
# 병합

In [24]:
df3 = pd.merge(df2, df1_1, on='case', how='outer')

In [25]:
df3

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,gender,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault
0,University of Virginia shooting,"Charlottesville, Virginia",Virginia,11/13/22,"Christopher Darnell Jones Jr., 22, allegedly o...",3,2,5,School,22,...,M,https://www.washingtonpost.com/nation/2022/11/...,-,-,-,-,Mass,2022,NaN,NaN
1,Raleigh spree shooting,"Hedingham, North Carolina",North Carolina,10/13/22,"Austin Thompson, 15, went on a rampage in the ...",5,2,7,Other,15,...,M,https://www.newsobserver.com/news/local/crime/...,-,-,-,-,Spree,2022,NaN,NaN
2,Greenwood Park Mall shooting,"Greenwood, Indiana",Indiana,7/17/22,"Jonathan Sapirman, 20, opened fire in a mall f...",3,2,5,workplace,20,...,M,https://apnews.com/article/indiana-mall-shooti...,-,-,-,-,Mass,2022,NaN,NaN
3,Highland Park July 4 parade shooting,"Highland Park, Illinois",Illinois,7/4/22,"Suspected gunman Robert ""Bobby"" Crimo, 21, all...",7,46,53,Other,21,...,M,https://www.cbsnews.com/chicago/news/suspect-i...,-,-,-,-,Mass,2022,NaN,NaN
4,Church potluck dinner shooting,"Birmingham, Alabama",Alabama,6/16/22,"Robert Findlay Smith, 70, opened fire with a h...",3,0,3,religious,70,...,M,https://apnews.com/article/alabama-birmingham-...,-,-,-,-,Mass,2022,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Shopping centers spree killings,"Palm Bay, Florida",Florida,4/23/1987,"Retired librarian William Cruse, 59, was paran...",6,14,20,Other,59,...,Male,http://articles.latimes.com/1987-04-25/news/mn...,(Supreme Court of Florida Document) http://www...,http://articles.latimes.com/1987-04-25/news/mn...,28.0331886,-80.6429695,Spree,1987,3.0,No
131,United States Postal Service shooting,"Edmond, Oklahoma",Oklahoma,8/20/1986,"Postal worker Patrick Sherrill, 44, opened fir...",15,6,21,Workplace,44,...,Male,http://news.google.com/newspapers?id=dm8aAAAAI...,http://newsok.com/sherrill-feared-mental-illne...,http://news.google.com/newspapers?id=dm8aAAAAI...,35.6672015,-97.42937037,Mass,1986,3.0,No
132,San Ysidro McDonald's massacre,"San Ysidro, California",California,7/18/1984,"James Oliver Huberty, 41, opened fire in a McD...",22,19,41,Other,41,...,Male,http://www.utsandiego.com/san-ysidro-massacre/...,http://www.nctimes.com/news/local/article_2ba4...,http://www.utsandiego.com/san-ysidro-massacre/...,32.5520013,-117.0430813,Mass,1984,3.0,Yes
133,Dallas nightclub shooting,"Dallas, Texas",Texas,6/29/1984,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,39,...,Male,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,32.925166,-96.838676,Mass,1984,1.0,No
134,Welding shop shooting,"Miami, Florida",Florida,8/20/1982,"Junior high school teacher Carl Robert Brown, ...",8,3,11,Other,51,...,Male,http://www.nytimes.com/1982/08/21/us/gunman-in...,http://news.google.com/newspapers?id=uuYLAAAAI...,http://www.nytimes.com/1982/08/21/us/gunman-in...,25.796491,-80.226683,Mass,1982,1.0,No

In [26]:
# date 컬럼 형식 통일 m/ d/ y ->> y-m-d - >> df3['chagedate']
# 그 후 pd.to_datetime ->> df3['dt']

In [27]:
df3['mon']= df3['date'].str.split('/').str.get(0)

In [28]:
df3['day']= df3['date'].str.split('/').str.get(1)

In [29]:
df3['stryear']= df3['date'].str.split('/').str.get(2)

In [30]:
df3[['mon','day','stryear']]

    mon day stryear
0    11  13      22
1    10  13      22
2     7  17      22
3     7   4      22
4     6  16      22
..   ..  ..     ...
130   4  23    1987
131   8  20    1986
132   7  18    1984
133   6  29    1984
134   8  20    1982

[135 rows x 3 columns]

In [31]:
def yearchange(stryear) :
    yeardic = {'17':'2017','18':'2018','19':'2019','20':'2020','21':'2021','22':'2022'}
    return yeardic.get(stryear)

In [32]:
df3.loc[0:46,'stryear'] = df3['stryear'].apply(yearchange)

In [33]:
df3[0:50]['stryear']

0     2022
1     2022
2     2022
3     2022
4     2022
5     2022
6     2022
7     2022
8     2022
9     2022
10    2021
11    2021
12    2021
13    2021
14    2021
15    2021
16    2020
17    2020
18    2019
19    2019
20    2019
21    2019
22    2019
23    2019
24    2019
25    2019
26    2019
27    2019
28    2018
29    2018
30    2018
31    2018
32    2018
33    2018
34    2018
35    2018
36    2018
37    2018
38    2018
39    2018
40    2017
41    2017
42    2017
43    2017
44    2017
45    2017
46    2017
47    2017
48    2017
49    2017
Name: stryear, dtype: object

In [34]:
yearstrlist=[str1 for str1 in df3['stryear']]

In [35]:
monstrlist=[str1 for str1 in df3['mon']]

In [36]:
daystrlist=[str1 for str1 in df3['day']]

In [37]:
datelist = []
for i in range(len(yearstrlist)) :
    datelist.append(  yearstrlist[i] + '-' + monstrlist[i] +  '-'  +daystrlist[i])

In [38]:
df3['chagedate'] = datelist

In [39]:
df3['dt'] = pd.to_datetime(df3['chagedate'], format="%Y-%m-%d")

In [40]:
# 기존 date 컬럼에  dt컬럼에서 추출한 날짜(str) 저장
df3['date'] = df3['dt'].dt.date

In [41]:

# 시분초 이슈 해결 : 추가 코드
# 2022-11-19 박기현
datetime_to_date= [dt.date() for dt in df3['dt']]
df3['dt'] = datetime_to_date

In [42]:
# 필요없는 컬럼 삭제

In [43]:
df3 = df3.drop(columns=['stryear','mon','day','chagedate'])

In [44]:
df3.T

,0,1,2,3,4,5,6,7,8,9,...,125,126,127,128,129,130,131,132,133,134
case,University of Virginia shooting,Raleigh spree shooting,Greenwood Park Mall shooting,Highland Park July 4 parade shooting,Church potluck dinner shooting,Concrete company shooting,Tulsa medical center shooting,Robb Elementary School massacre,Buffalo supermarket massacre,Sacramento County church shooting,...,Luby's massacre,GMAC massacre,Standard Gravure shooting,Stockton schoolyard shooting,ESL shooting,Shopping centers spree killings,United States Postal Service shooting,San Ysidro McDonald's massacre,Dallas nightclub shooting,Welding shop shooting
location,"Charlottesville, Virginia","Hedingham, North Carolina","Greenwood, Indiana","Highland Park, Illinois","Birmingham, Alabama","Smithsburg, Maryland","Tulsa, Oklahoma","Uvalde, Texas","Buffalo, New York","Sacramento, California",...,"Killeen, Texas","Jacksonville, Florida","Louisville, Kentucky","Stockton, California","Sunnyvale, California","Palm Bay, Florida","Edmond, Oklahoma","San Ysidro, California","Dallas, Texas","Miami, Florida"
state,Virginia,North Carolina,Indiana,Illinois,Alabama,Maryland,Oklahoma,Texas,New York,California,...,Texas,Florida,Kentucky,California,California,Florida,Oklahoma,California,Texas,Florida
date,2022-11-13,2022-10-13,2022-07-17,2022-07-04,2022-06-16,2022-06-09,2022-06-01,2022-05-24,2022-05-14,2022-02-28,...,1991-10-16,1990-06-18,1989-09-14,1989-01-17,1988-02-16,1987-04-23,1986-08-20,1984-07-18,1984-06-29,1982-08-20
summary,"Christopher Darnell Jones Jr., 22, allegedly o...","Austin Thompson, 15, went on a rampage in the ...","Jonathan Sapirman, 20, opened fire in a mall f...","Suspected gunman Robert ""Bobby"" Crimo, 21, all...","Robert Findlay Smith, 70, opened fire with a h...",The suspected 23-year-old gunman shot four cow...,"Michael Louis, 45, killed four, including two ...","Salvador Ramos, 18, was identified by authorit...","Payton S. Gendron, 18, committed a racially mo...","""A man believed to be meeting his three childr...",...,"George Hennard, 35, drove his pickup truck int...","James Edward Pough, 42, opened fire at a Gener...","Joseph T. Wesbecker, 47, gunned down eight peo...","Patrick Purdy, 26, an alcoholic with a police ...",Former ESL Incorporated employee Richard Farle...,"Retired librarian William Cruse, 59, was paran...","Postal worker Patrick Sherrill, 44, opened fir...","James Oliver Huberty, 41, opened fire in a McD...","Abdelkrim Belachheb, 39, opened fire at an ups...","Junior high school teacher Carl Robert Brown, ..."
fatalities,3,5,3,7,3,3,4,21,10,4,...,24,10,9,6,7,6,15,22,6,8
injured,2,2,2,46,0,1,"(TK - ""fewer than 10""",17,3,0,...,20,4,12,29,4,14,6,19,1,3
total_victims,5,7,5,53,3,4,TK,38,13,4,...,44,14,21,35,11,20,21,41,7,11
location.1,School,Other,workplace,Other,religious,workplace,workplace,School,workplace,Religious,...,Other,Other,Workplace,School,Workplace,Other,Workplace,Other,Other,Other
age_of_shooter,22,15,20,21,70,23,-,18,18,-,...,35,42,47,26,39,59,44,41,39,51
prior_signs_mental_health_issues,-,-,-,-,-,-,-,yes,yes,-,...,No,No,Yes,Yes,Yes,Yes,Unclear,Yes,Yes,Yes
mental_health_details,-,-,-,-,-,-,-,-,previous threats and a mental health evaluatio...,-,...,"Acquaintances described him as troubled, unsta...","Police speculated he had a ""grudge"" against th...","Prior to the shooting, he had voluntarily chec...","He told a mental health professional he was ""s...",He stalked and harassed his colleague Laura Bl...,He suffered from paranoid delusions. A judge f...,He was worried he had inherited mental problem...,"The day before the shooting, he tried to make ...","During his last meal with his wife, he confess...",His second wife left him because he refused to...
weapons_obtained_legally,-,-,yes,yes,yes,-,yes,yes,yes,-,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes
where_obtained,-,-,in Greenwood,"legally purchased by the shooter in the ""great...",-,-,-,-,-,-,...,"Mike's Gun Shop in Henderson, Nev.",Unknown,AK-47 purchased from Tilford's Gun Sales in Lo...,"Sandy Trading Post in Sandy, Ore.; Hunter Loan...",Various sporting goods and gun stores in North...,"Gun store in Norwood, Ohio; The Oaks Trading P...","Issued by Oklahoma National Guard, where Sherr...",Unknown,"Hines Boulevard Pawn Shop in Dallas, Texas","Garcia Gun Center in Hialeah, Fla."
weapon_type,-,"semiautomatic rifle, semiautomatic handgun",semiautomatic rifles; semiautomatic handgun,semiautomatic rifle,semiautomatic handgun,-,semiautomatic rifle; semiautomatic handgun,semiautomatic rifles,semiautomatic rifle,-,...,Two semiautomatic handguns,"One rifle, one revolver","Three semiautomatic handguns (two assault), on...","One semiautomatic handgun, one rifle (assault)","Two semiautomatic handguns, one rifle, two rev...","One rifle, one revolver, one shotgun",Three semiautomatic handguns,"One semiautomatic handgun, one rifle (assault)...",One semiautomatic handgun,One shotgun
weapon_details,-,NaN,Sig Sauer M400 rifle,"AR-15 style rifle, possibly modified for rapid...",-,-,AR-15 style rifle,-,Bushmaster XM-15 semiautomatic rifle,-,...,"9mm Glock 17, 9mm Ruger P89 semiautomatic hand...",.30-caliber Universal M1 carbine rifle; .38-ca...,"Two Intratec MAC-11, 9mm SIG Sauer semiautomat...",9mm Taurus semiautomatic handgun; AK-47 Chines...,".380 ACP Browning, 9mm Smith & Wesson semiauto...","Sturm, Ruger Mini-14 semiautomatic rifle; 20-g...",".22-caliber, two .45-caliber Colt Model 1911-A...",9mm Browning P35 Hi-Power semiautomatic handgu...,9mm Smith & Wesson 459 semiautomatic handgun,Mossberg 500 Persuader pump-action shotgun wit...
race,Black,White,White,White,White,-,Black,Latino,White,-,...,white,black,white,white,white,white,white,white,white,white
gender,M,M,M,M,M,M,M,M,M,M,...,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male
sources,https://www.washingtonpost.com/nation/2022/11/...,https://www.newsobserver.com/news/local/crime/...,https://apnews.com/article/indiana-mall-shooti...,https://www.cbsnews.com/chicago/news/suspect-i...,https://apnews.com/article/alabama-birmingham-...,https://www.washingtonpost.com/dc-md-va/2022/0...,https://www.nytimes.com/live/2022/06/01/us/tul...,https://abcnews.go.com/US/texas-elementary-sch...,https://www.nytimes.com/live/2022/05/15/nyregi...,https://www.nytimes.com/2022/02/28/us/church-s...,...,http://www.nytimes.com/1991/10/18/us/portrait-...,http://www.nytimes.com/1990/06/19/us/florida-g...,http://nl.newsbank.com/nl-search/we/Archives?p...,http://www.recordnet.com/apps/pbcs.dll/article...,http://articles.latimes.com/1988-02-18/news/mn...,http://articles.latimes.com/1987-04-25/news/mn...,http://news.google.com/newspapers?id=dm8aAAAAI...,http://www.utsandiego.com/san-ysidro-massacre/...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://www.nytimes.com/1982/08/21/us/gunman-in...
mental_health_sources,-,-,-,-,-,-,-,-,https://www.nytimes.com/2022/05/15/nyregion/gu...,-,...,http://www.nytimes.com/1991/10/20/weekinreview...,http://www.nytimes.com/1990/06/20/us/hazy-reco...,http://www.nytimes.com/1989/09/16/us/disturbed...,http://www.recordnet.com/apps/pbcs.dll/article...,http://books.google.com/books?id=JiQUkwBnzgYC&...,(Supreme Court of Florida Document) http://www...,http://newsok.com/sherrill-feared-mental-illne...,http://www.nctimes.com/news/local/article_2ba4...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://news.google.com/newspapers?id=uuYLAAAAI...
sources_additional_age,-,-,-,-,-,-,-,-,-,-,...,http://www.nytimes.com/1991/10/18/us/portrait-...,http://www.nytimes.com/1990/06/19/us/florida-g...,http://nl.newsbank.com/nl-search/we/Archives?p...,http://www.recordnet.com/apps/pbcs.dll/article...,http://articles.latimes.com/1988-02-18/news/mn...,http://articles.latimes.com/1987-04-25/news/mn...,http://news.google.com/newspapers?id=dm8aAAAAI...,http://www.utsandiego.com/san-ysidro-massacre/...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://www.nytimes.com/1982/08/21/us/gunman-in...
latitude,-,-,-,-,-,-,-,-,-,38.60111019,...,31.1171194,30.3321838,38.2542376,37.9577016,37.3688301,28.0331886,35.6672015,32.5520013,32.925166,25.796491
longitude,-,-,-,-,-,-,-,-,-,-121.4189659,...,-97.7277959,-81.655651,-85.759407,-121.2907796,-122.0363496,-80.6429695,-97.42937037,-117.0430813,-96.838676,-80.226683
type,Mass,Spree,Mass,Mass,Mass,Mass,Mass,Mass,Mass,Mass,...,Mass,Mass,Mass,Mass,Mass,Spree,Mass,Mass,Mass,Mass
year,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,1991,1990,1989,1989,1988,1987,1986,1984,1984,1982
numweapons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2.0,5.0,2.0,7.0,3.0,3.0,3.0,1.0,1.0
assault,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,No,Yes,Yes,No,No,No,Yes,No,No
dt,2022-11-13,2022-10-13,2022-07-17,2022-07-04,2022-06-16,2022-06-09,2022-06-01,2022-05-24,2022-05-14,2022-02-28,...,1991-10-16,1990-06-18,1989-09-14,1989-01-17,1988-02-16,1987-04-23,1986-08-20,1984-07-18,1984-06-29,1982-08-20

In [45]:
# df3의 결측값 처리

In [46]:
# 1. 결측값데이터 '-' -> NaN 값으로 변환

In [47]:
df3 = df3.replace('-', np.NaN)

In [48]:
# 2. 결측값 존재하는 컬럼 확인

In [49]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       5
prior_signs_mental_health_issues    24
mental_health_details               38
weapons_obtained_legally            14
where_obtained                      41
weapon_type                          6
weapon_details                      23
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             9
longitude                            9
type                                 0
year                                 0
numweapons                          64
assault                             64
dt                                   0
dtype: int64

In [50]:
# age_of_shooter 컬럼의 결측치 처리

In [51]:
# 결측값을 가진 행 확인 -> summary에서 나이 발췌 가능한 행 확인 (6, 13, 18 인덱스 확인)

In [52]:
df3[df3['age_of_shooter'].isnull()]

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault,dt
6,Tulsa medical center shooting,"Tulsa, Oklahoma",Oklahoma,2022-06-01,"Michael Louis, 45, killed four, including two ...",4,"(TK - ""fewer than 10""",TK,workplace,NaN,...,https://www.nytimes.com/live/2022/06/01/us/tul...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-06-01
9,Sacramento County church shooting,"Sacramento, California",California,2022-02-28,"""A man believed to be meeting his three childr...",4,0,4,Religious,NaN,...,https://www.nytimes.com/2022/02/28/us/church-s...,NaN,NaN,38.60111019,-121.4189659,Mass,2022,NaN,NaN,2022-02-28
13,Orange office complex shooting,"Orange, California",California,2021-03-31,"Aminadab Gaxiola Gonzalez, 44, allegedly opene...",4,1,5,Workplace,NaN,...,https://www.latimes.com/california/story/2021-...,NaN,NaN,33.83542,-117.85379,Mass,2021,NaN,NaN,2021-03-31
18,Jersey City kosher market shooting,"Jersey City, New Jersey",New Jersey,2019-12-10,"David N. Anderson, 47, and Francine Graham, 50...",4,3,7,Other,NaN,...,https://www.nytimes.com/2019/12/15/nyregion/je...,NaN,NaN,40.707363,-74.083609,Spree,2019,NaN,NaN,2019-12-10
19,Pensacola Naval base shooting,"Pensacola, Florida",Florida,2019-12-06,"Ahmed Mohammed al-Shamrani, A Saudi Arabian mi...",3,8,11,Military,NaN,...,https://www.washingtonpost.com/national-securi...,NaN,NaN,30.364707,-87.288567,Mass,2019,NaN,NaN,2019-12-06

In [53]:
# df3의 6, 13, 18번 인덱스만 적용가능

In [54]:
age = df3[df3['age_of_shooter'].isnull()]['summary'].str.split(',').str.get(1).str.split()

In [55]:
df3.loc[6,'age_of_shooter'] = age[6][0]

In [56]:
df3.loc[13,'age_of_shooter'] = age[13][0]

In [57]:
df3.loc[18,'age_of_shooter'] = age[18][0]

In [58]:
# NaN값이 있을때 정수형 변환 불가, 실수형으로만 가능

In [59]:
# NaN값을 0으로 바꾸는 방법은 x --> 범죄자 최소연령에 영향

In [60]:
# NaN값을 가지는 df3[9, 19 인덱스] 값은 case 검색하여 직접 데이터 추가

In [61]:
# 출처
# https://www.kcra.com/article/sacramento-church-father-kills-3-daughters-what-we-know/39302856
# https://en.wikipedia.org/wiki/Naval_Air_Station_Pensacola_shooting#Perpetrator

In [62]:
df3[df3['age_of_shooter'].isnull()]['case']

9     Sacramento County church shooting
19        Pensacola Naval base shooting
Name: case, dtype: object

In [63]:
df3.loc[9,'age_of_shooter'] = '39'

In [64]:
df3.loc[19,'age_of_shooter'] = '21'

In [65]:
df3.loc[6:13]

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault,dt
6,Tulsa medical center shooting,"Tulsa, Oklahoma",Oklahoma,2022-06-01,"Michael Louis, 45, killed four, including two ...",4,"(TK - ""fewer than 10""",TK,workplace,45,...,https://www.nytimes.com/live/2022/06/01/us/tul...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-06-01
7,Robb Elementary School massacre,"Uvalde, Texas",Texas,2022-05-24,"Salvador Ramos, 18, was identified by authorit...",21,17,38,School,18,...,https://abcnews.go.com/US/texas-elementary-sch...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-05-24
8,Buffalo supermarket massacre,"Buffalo, New York",New York,2022-05-14,"Payton S. Gendron, 18, committed a racially mo...",10,3,13,workplace,18,...,https://www.nytimes.com/live/2022/05/15/nyregi...,https://www.nytimes.com/2022/05/15/nyregion/gu...,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-05-14
9,Sacramento County church shooting,"Sacramento, California",California,2022-02-28,"""A man believed to be meeting his three childr...",4,0,4,Religious,39,...,https://www.nytimes.com/2022/02/28/us/church-s...,NaN,NaN,38.60111019,-121.4189659,Mass,2022,NaN,NaN,2022-02-28
10,Oxford High School shooting,"Oxford, Michigan",Michigan,2021-11-30,"Ethan Crumbley, a 15-year-old student at Oxfor...",4,7,11,School,15,...,https://www.washingtonpost.com/nation/2021/11/...,NaN,NaN,42.84410784,-83.25992831,Mass,2021,NaN,NaN,2021-11-30
11,San Jose VTA shooting,"San Jose, California",California,2021-05-26,"Samuel Cassidy, 57, a Valley Transportation Au...",9,0,9,Workplace,57,...,https://www.sfchronicle.com/crime/article/Mass...,https://www.nytimes.com/2021/05/26/us/what-hap...,NaN,37.316097,-121.888533,Mass,2021,NaN,NaN,2021-05-26
12,FedEx warehouse shooting,"Indianapolis, Indiana",Indiana,2021-04-15,"Brandon Scott Hole, 19, opened fire around 11 ...",8,7,15,Workplace,19,...,https://www.indystar.com/story/news/crime/2021...,https://www.nytimes.com/2021/04/19/us/indianap...,NaN,39.68663,-86.32313,Mass,2021,NaN,NaN,2021-04-15
13,Orange office complex shooting,"Orange, California",California,2021-03-31,"Aminadab Gaxiola Gonzalez, 44, allegedly opene...",4,1,5,Workplace,44,...,https://www.latimes.com/california/story/2021-...,NaN,NaN,33.83542,-117.85379,Mass,2021,NaN,NaN,2021-03-31

In [66]:
# 데이터 타입 변경

In [67]:
# age_of_shooter, fatalities, injured, total_victims 컬럼 작업

In [68]:
df3['age_of_shooter'] = pd.to_numeric(df3['age_of_shooter'])

In [69]:
df3['fatalities'] = pd.to_numeric(df3['fatalities'])

In [70]:
# injured, total_victims 컬럼의 value에 문자열 확인 -> 인덱스 6번 행

In [71]:
# 기사내용 : 불특정 다수의 부상자 (직접적인 수치 언급 x)
        # 출처 : https://en.wikipedia.org/wiki/2022_Tulsa_hospital_shooting

In [72]:
# 사망자가 4명인 사건의  부상자 평균값 사용

In [73]:
injured_mean = pd.to_numeric(df3[df3['fatalities']==4]['injured'][1:])

In [74]:
injured_mean = round(injured_mean.mean())

In [75]:
df3.loc[6,'injured'] = injured_mean

In [76]:
df3.loc[6,'total_victims'] = df3.loc[6,'fatalities'] + df3.loc[6,'injured']

In [77]:
df3['injured'] = pd.to_numeric(df3['injured'])

In [78]:
df3['total_victims'] = pd.to_numeric(df3['total_victims'])

In [79]:
# gender value값 일치시키기

In [80]:
df3['gender'].value_counts()

Male             70
M                60
Male & Female     2
Female            2
F                 1
Name: gender, dtype: int64

In [81]:
def gender_name(gender_name) :
    gender_dict = {'M':'Male', 'Male':'Male' , 'Female':'Female' ,'F':'Female', 'Male & Female':'Male & Female' }
    return gender_dict.get(gender_name)

In [82]:
df3['gender'] = df3['gender'].apply(gender_name)

In [83]:
# 경도 위도 빈 행 찾기

In [84]:
df_lat = df3[df3['latitude'].isnull()]
df_lat

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault,dt
0,University of Virginia shooting,"Charlottesville, Virginia",Virginia,2022-11-13,"Christopher Darnell Jones Jr., 22, allegedly o...",3,2,5,School,22,...,https://www.washingtonpost.com/nation/2022/11/...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-11-13
1,Raleigh spree shooting,"Hedingham, North Carolina",North Carolina,2022-10-13,"Austin Thompson, 15, went on a rampage in the ...",5,2,7,Other,15,...,https://www.newsobserver.com/news/local/crime/...,NaN,NaN,NaN,NaN,Spree,2022,NaN,NaN,2022-10-13
2,Greenwood Park Mall shooting,"Greenwood, Indiana",Indiana,2022-07-17,"Jonathan Sapirman, 20, opened fire in a mall f...",3,2,5,workplace,20,...,https://apnews.com/article/indiana-mall-shooti...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-07-17
3,Highland Park July 4 parade shooting,"Highland Park, Illinois",Illinois,2022-07-04,"Suspected gunman Robert ""Bobby"" Crimo, 21, all...",7,46,53,Other,21,...,https://www.cbsnews.com/chicago/news/suspect-i...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-07-04
4,Church potluck dinner shooting,"Birmingham, Alabama",Alabama,2022-06-16,"Robert Findlay Smith, 70, opened fire with a h...",3,0,3,religious,70,...,https://apnews.com/article/alabama-birmingham-...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-06-16
5,Concrete company shooting,"Smithsburg, Maryland",Maryland,2022-06-09,The suspected 23-year-old gunman shot four cow...,3,1,4,workplace,23,...,https://www.washingtonpost.com/dc-md-va/2022/0...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-06-09
6,Tulsa medical center shooting,"Tulsa, Oklahoma",Oklahoma,2022-06-01,"Michael Louis, 45, killed four, including two ...",4,5,9,workplace,45,...,https://www.nytimes.com/live/2022/06/01/us/tul...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-06-01
7,Robb Elementary School massacre,"Uvalde, Texas",Texas,2022-05-24,"Salvador Ramos, 18, was identified by authorit...",21,17,38,School,18,...,https://abcnews.go.com/US/texas-elementary-sch...,NaN,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-05-24
8,Buffalo supermarket massacre,"Buffalo, New York",New York,2022-05-14,"Payton S. Gendron, 18, committed a racially mo...",10,3,13,workplace,18,...,https://www.nytimes.com/live/2022/05/15/nyregi...,https://www.nytimes.com/2022/05/15/nyregion/gu...,NaN,NaN,NaN,Mass,2022,NaN,NaN,2022-05-14

In [85]:
df_lat_loc = df_lat['location']
df_lat_loc

0    Charlottesville, Virginia
1    Hedingham, North Carolina
2           Greenwood, Indiana
3      Highland Park, Illinois
4          Birmingham, Alabama
5         Smithsburg, Maryland
6              Tulsa, Oklahoma
7                Uvalde, Texas
8            Buffalo, New York
Name: location, dtype: object

In [86]:
# geocoding 이용으로 위도 경도값 가져오기
# import 하기 전에 anaconda prompt에서 pip install geopy 입력으로 설치해줘야 함

In [87]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='United States')

In [88]:
def geocoding(df_lat_loc):
    try:
        geo = geo_local.geocode(df_lat_loc)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

In [89]:
latitude = []
longitude = []

for i in df_lat_loc:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [90]:
location_df = pd.DataFrame({'location': df_lat_loc,'latitude':latitude,'longitude':longitude})

# 결과 확인
location_df

                    location   latitude  longitude
0  Charlottesville, Virginia  38.029306 -78.476678
1  Hedingham, North Carolina  35.810178 -78.548364
2         Greenwood, Indiana  39.613658 -86.106653
3    Highland Park, Illinois  42.181692 -87.800344
4        Birmingham, Alabama  33.520682 -86.802433
5       Smithsburg, Maryland  39.654819 -77.572768
6            Tulsa, Oklahoma  36.156312 -95.992744
7              Uvalde, Texas  29.300357 -99.773318
8          Buffalo, New York  42.886717 -78.878392

In [91]:
df3.loc[0:8,'latitude'] = location_df.loc[0:8,'latitude']
df3.loc[0:8,'longitude'] = location_df.loc[0:8,'longitude']

In [92]:
# numweapons NaN 값 처리

In [93]:
# weapon_type 중 형식이 벗어난 데이터 별도로 처리

#https://en.wikipedia.org/wiki/2017_Las_Vegas_shooting#Weaponry 준비 24정, 실사용 15정
df3.loc[44,'numweapons'] = 24

#df3.loc[57,'weapon_type'] 토대로 작성
df3.loc[57,'numweapons'] = 4

In [94]:
# weapon_type 중 nan 값 확인
df3[df3['weapon_type'].isnull()][['case','dt','weapon_type','weapon_details','numweapons']]

,case,dt,weapon_type,weapon_details,numweapons
0,University of Virginia shooting,2022-11-13,NaN,NaN,NaN
5,Concrete company shooting,2022-06-09,NaN,NaN,NaN
9,Sacramento County church shooting,2022-02-28,NaN,NaN,NaN
15,Atlanta massage parlor shootings,2021-03-16,NaN,NaN,NaN
16,Springfield convenience store shooting,2020-03-16,NaN,NaN,NaN
18,Jersey City kosher market shooting,2019-12-10,NaN,NaN,NaN

In [95]:
# 자료 추가
#https://www.nbcnews.com/news/us-news/3-dead-2-injured-shooting-university-virginia-rcna57004
df3.loc[0,'weapon_type'] = 'handgun'
#https://www.washingtonpost.com/dc-md-va/2022/06/09/smithsburg-shooting-maryland/
df3.loc[5,'weapon_type'] = 'semiautomatic handgun'
#https://www.forbes.com/sites/siladityaray/2022/03/01/five-people-including-three-children-dead-in-murder-suicide-shooting-at-sacramento-church/?sh=79d7e1903ae2
df3.loc[9,'weapon_type'] = 'semiautomatic rifle'
#https://en.wikipedia.org/wiki/2021_Atlanta_spa_shootings
df3.loc[15,'weapon_type'] = 'semiautomatic pistol'
#https://en.wikipedia.org/wiki/2020_Springfield,_Missouri_shooting
df3.loc[16,'weapon_type'] = 'semiautomatic rifle, semiautomatic pistol'
#https://en.wikipedia.org/wiki/2019_Jersey_City_shooting#Assailants
df3.loc[18,'weapon_type'] = 'two semiautomatic rifle, two handgun'

In [96]:
# weapon_type 데이터를 가공할 함수 생성
def weapon_num(weapon_type) :
    num=0
    weapon_type_list = weapon_type.split(',')
    for weapon in weapon_type_list :
        if 'five' in weapon :
            num += 5
        elif 'three' in weapon :
            num += 3
        elif 'two' in weapon :
            num += 2
        else :
            num += 1
        
    return num

In [97]:
# 적용, 임시로 생성한 컬럼 제거, 타입변환 
df3['weapon_type_test'] = df3['weapon_type'].str.lower().str.replace('handgun','HG').str.replace('and',',').str.replace(';',',').str.replace('2','two')
df3.loc[df3['numweapons'].isnull(),'numweapons'] = df3[df3['numweapons'].isnull()]['weapon_type_test'].apply(weapon_num)
df3 = df3.drop(columns='weapon_type_test')
df3 = df3.astype({'numweapons':'int'})
df3

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault,dt
0,University of Virginia shooting,"Charlottesville, Virginia",Virginia,2022-11-13,"Christopher Darnell Jones Jr., 22, allegedly o...",3,2,5,School,22,...,https://www.washingtonpost.com/nation/2022/11/...,NaN,NaN,38.029306,-78.476678,Mass,2022,1,NaN,2022-11-13
1,Raleigh spree shooting,"Hedingham, North Carolina",North Carolina,2022-10-13,"Austin Thompson, 15, went on a rampage in the ...",5,2,7,Other,15,...,https://www.newsobserver.com/news/local/crime/...,NaN,NaN,35.810178,-78.548364,Spree,2022,2,NaN,2022-10-13
2,Greenwood Park Mall shooting,"Greenwood, Indiana",Indiana,2022-07-17,"Jonathan Sapirman, 20, opened fire in a mall f...",3,2,5,workplace,20,...,https://apnews.com/article/indiana-mall-shooti...,NaN,NaN,39.613658,-86.106653,Mass,2022,2,NaN,2022-07-17
3,Highland Park July 4 parade shooting,"Highland Park, Illinois",Illinois,2022-07-04,"Suspected gunman Robert ""Bobby"" Crimo, 21, all...",7,46,53,Other,21,...,https://www.cbsnews.com/chicago/news/suspect-i...,NaN,NaN,42.181692,-87.800344,Mass,2022,1,NaN,2022-07-04
4,Church potluck dinner shooting,"Birmingham, Alabama",Alabama,2022-06-16,"Robert Findlay Smith, 70, opened fire with a h...",3,0,3,religious,70,...,https://apnews.com/article/alabama-birmingham-...,NaN,NaN,33.520682,-86.802433,Mass,2022,1,NaN,2022-06-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Shopping centers spree killings,"Palm Bay, Florida",Florida,1987-04-23,"Retired librarian William Cruse, 59, was paran...",6,14,20,Other,59,...,http://articles.latimes.com/1987-04-25/news/mn...,(Supreme Court of Florida Document) http://www...,http://articles.latimes.com/1987-04-25/news/mn...,28.0331886,-80.6429695,Spree,1987,3,No,1987-04-23
131,United States Postal Service shooting,"Edmond, Oklahoma",Oklahoma,1986-08-20,"Postal worker Patrick Sherrill, 44, opened fir...",15,6,21,Workplace,44,...,http://news.google.com/newspapers?id=dm8aAAAAI...,http://newsok.com/sherrill-feared-mental-illne...,http://news.google.com/newspapers?id=dm8aAAAAI...,35.6672015,-97.42937037,Mass,1986,3,No,1986-08-20
132,San Ysidro McDonald's massacre,"San Ysidro, California",California,1984-07-18,"James Oliver Huberty, 41, opened fire in a McD...",22,19,41,Other,41,...,http://www.utsandiego.com/san-ysidro-massacre/...,http://www.nctimes.com/news/local/article_2ba4...,http://www.utsandiego.com/san-ysidro-massacre/...,32.5520013,-117.0430813,Mass,1984,3,Yes,1984-07-18
133,Dallas nightclub shooting,"Dallas, Texas",Texas,1984-06-29,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,39,...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,32.925166,-96.838676,Mass,1984,1,No,1984-06-29
134,Welding shop shooting,"Miami, Florida",Florida,1982-08-20,"Junior high school teacher Carl Robert Brown, ...",8,3,11,Other,51,...,http://www.nytimes.com/1982/08/21/us/gunman-in...,http://news.google.com/newspapers?id=uuYLAAAAI...,http://www.nytimes.com/1982/08/21/us/gunman-in...,25.796491,-80.226683,Mass,1982,1,No,1982-08-20

In [98]:
df3[['numweapons','weapon_type']][0 : 50]

    numweapons                                        weapon_type
0            1                                            handgun
1            2         semiautomatic rifle, semiautomatic handgun
2            2        semiautomatic rifles; semiautomatic handgun
3            1                                semiautomatic rifle
4            1                              semiautomatic handgun
5            1                              semiautomatic handgun
6            2         semiautomatic rifle; semiautomatic handgun
7            1                               semiautomatic rifles
8            1                                semiautomatic rifle
9            1                                semiautomatic rifle
10           1                              semiautomatic handgun
11           1                             semiautomatic handguns
12           1                                semiautomatic rifle
13           1                              semiautomatic handgun
14           3  semiautomatic rifle, semiautomatic handgun; ta...
15           1                               semiautomatic pistol
16           2          semiautomatic rifle, semiautomatic pistol
17           1                              semiautomatic handgun
18           4               two semiautomatic rifle, two handgun
19           1                              semiautomatic handgun
20           1                                semiautomatic rifle
21           1                                semiautomatic rifle
22           1                                semiautomatic rifle
23           1                                semiautomatic rifle
24           2                                         2 handguns
25           1                                            handgun
26           1                                            handgun
27           1                                            handgun
28           1                              semiautomatic handgun
29           1                              semiautomatic handgun
30           2        semiautomatic rifle; semiautomatic handguns
31           1                              semiautomatic handgun
32           1                                            handgun
33           1                              semiautomatic handgun
34           1                                            shotgun
35           2                              shotgun; .38 revolver
36           1                                semiautomatic rifle
37           2                       semiautomatic rifle; shotgun
38           1                                semiautomatic rifle
39           2      semiautomatic rifle and semiautomatic handgun
40           1                               semiautomatic rifles
41           1                                semiautomatic rifle
42           1                              semiautomatic handgun
43           1                                            handgun
44          24  23 firearms, mostly rifles; including scopes, ...
45           2                                       two handguns
46           1                                           shotguns
47           1                              semiautomatic handgun
48           2                                   handgun, shotgun
49           1                                            handgun

In [99]:
df3

,case,location,state,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,...,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,numweapons,assault,dt
0,University of Virginia shooting,"Charlottesville, Virginia",Virginia,2022-11-13,"Christopher Darnell Jones Jr., 22, allegedly o...",3,2,5,School,22,...,https://www.washingtonpost.com/nation/2022/11/...,NaN,NaN,38.029306,-78.476678,Mass,2022,1,NaN,2022-11-13
1,Raleigh spree shooting,"Hedingham, North Carolina",North Carolina,2022-10-13,"Austin Thompson, 15, went on a rampage in the ...",5,2,7,Other,15,...,https://www.newsobserver.com/news/local/crime/...,NaN,NaN,35.810178,-78.548364,Spree,2022,2,NaN,2022-10-13
2,Greenwood Park Mall shooting,"Greenwood, Indiana",Indiana,2022-07-17,"Jonathan Sapirman, 20, opened fire in a mall f...",3,2,5,workplace,20,...,https://apnews.com/article/indiana-mall-shooti...,NaN,NaN,39.613658,-86.106653,Mass,2022,2,NaN,2022-07-17
3,Highland Park July 4 parade shooting,"Highland Park, Illinois",Illinois,2022-07-04,"Suspected gunman Robert ""Bobby"" Crimo, 21, all...",7,46,53,Other,21,...,https://www.cbsnews.com/chicago/news/suspect-i...,NaN,NaN,42.181692,-87.800344,Mass,2022,1,NaN,2022-07-04
4,Church potluck dinner shooting,"Birmingham, Alabama",Alabama,2022-06-16,"Robert Findlay Smith, 70, opened fire with a h...",3,0,3,religious,70,...,https://apnews.com/article/alabama-birmingham-...,NaN,NaN,33.520682,-86.802433,Mass,2022,1,NaN,2022-06-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Shopping centers spree killings,"Palm Bay, Florida",Florida,1987-04-23,"Retired librarian William Cruse, 59, was paran...",6,14,20,Other,59,...,http://articles.latimes.com/1987-04-25/news/mn...,(Supreme Court of Florida Document) http://www...,http://articles.latimes.com/1987-04-25/news/mn...,28.0331886,-80.6429695,Spree,1987,3,No,1987-04-23
131,United States Postal Service shooting,"Edmond, Oklahoma",Oklahoma,1986-08-20,"Postal worker Patrick Sherrill, 44, opened fir...",15,6,21,Workplace,44,...,http://news.google.com/newspapers?id=dm8aAAAAI...,http://newsok.com/sherrill-feared-mental-illne...,http://news.google.com/newspapers?id=dm8aAAAAI...,35.6672015,-97.42937037,Mass,1986,3,No,1986-08-20
132,San Ysidro McDonald's massacre,"San Ysidro, California",California,1984-07-18,"James Oliver Huberty, 41, opened fire in a McD...",22,19,41,Other,41,...,http://www.utsandiego.com/san-ysidro-massacre/...,http://www.nctimes.com/news/local/article_2ba4...,http://www.utsandiego.com/san-ysidro-massacre/...,32.5520013,-117.0430813,Mass,1984,3,Yes,1984-07-18
133,Dallas nightclub shooting,"Dallas, Texas",Texas,1984-06-29,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,39,...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,http://books.google.com/books?id=Hr3OBwP-lbUC&...,32.925166,-96.838676,Mass,1984,1,No,1984-06-29
134,Welding shop shooting,"Miami, Florida",Florida,1982-08-20,"Junior high school teacher Carl Robert Brown, ...",8,3,11,Other,51,...,http://www.nytimes.com/1982/08/21/us/gunman-in...,http://news.google.com/newspapers?id=uuYLAAAAI...,http://www.nytimes.com/1982/08/21/us/gunman-in...,25.796491,-80.226683,Mass,1982,1,No,1982-08-20

In [100]:
# 2022_11_20 박기현

# 구글 search api를 활용한 numsearchresult 데이터 추가하기

# 주의 : 구글 search api는 일일 할당량이 작습니다. 코드 실행 시 매번 결과가 다를 수 있습니다.

# 확인 목적이 아니면, 별도로 올린 csv 파일을 불러와 사용하는 것을 권장합니다.
# https://developers.google.com/custom-search/v1/using_rest
# 테스트 시, REST_API_KEY 를 바꿔가며 실행해야함.
# 할당량 문제로 다른 누군가 실행하면 데이터를 가져올 수 없습니다.

# GET https://www.googleapis.com/customsearch/v1?key=INSERT_YOUR_API_KEY&cx={search_engine}&q={query}
# --header 'Accept: application/json' \
# 
def totalResults(query) : 
    import requests
    # 첫번째 api 키
    REST_API_KEY = 'AIzaSyB-kzW8S8MeqMFgda3KfVMfU-WsafGVqPk'
    # 두번째 api 키
    #REST_API_KEY ='AIzaSyCawk2cS0kAhwds51GNAFJ7I_VnY_Nl8UE'
    search_engine = 'c5d01fea928154329'
    url =f'https://www.googleapis.com/customsearch/v1?key={REST_API_KEY}&cx={search_engine}&q={query}'
    headers = {"Accept": "application/json"}
    r = requests.get(url, headers=headers)
    data = r.json()
    try:
        return data['queries']['request'][0]['totalResults']
    except:
        return '할당초과'
    
    
# 첫번째 api 키
#df3['numsearchresult'] = df3['case'].apply(totalResults)


def totalResults(query) : 
    import requests
    # 첫번째 api 키
    #REST_API_KEY = 'AIzaSyB-kzW8S8MeqMFgda3KfVMfU-WsafGVqPk'
    # 두번째 api 키
    REST_API_KEY ='AIzaSyCawk2cS0kAhwds51GNAFJ7I_VnY_Nl8UE'
    search_engine = 'c5d01fea928154329'
    url =f'https://www.googleapis.com/customsearch/v1?key={REST_API_KEY}&cx={search_engine}&q={query}'
    headers = {"Accept": "application/json"}
    r = requests.get(url, headers=headers)
    data = r.json()
    try:
        return data['queries']['request'][0]['totalResults']
    except:
        return '할당초과'
    
    
# 할당량 초과 후 데이터 받기
# 두번째 api 키
#df3.loc[df3['numsearchresult']=='할당초과','numsearchresult'] = df3[df3['numsearchresult']=='할당초과']['case'].apply(totalResults)

In [101]:

# 저장 위치
#df3.to_csv("data/df3_20221120_jcr_01.csv")

In [102]:
# api 할당량 문제로 적용된 데이터를 불러옵니다.
df3 = pd.read_csv('data/df3_20221120_jcr_01.csv')
#저장할 때 생기는 불필요한 컬럼 제거
df3 = df3.drop(columns='Unnamed: 0')

In [103]:
#  prior_signs_mental_health_issues NaN값 처리. 11월 20일 심재훈

In [104]:
# 전체 데이터에서 결측치가 있는 값을 찾아내기

df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues    24
mental_health_details               38
weapons_obtained_legally            14
where_obtained                      41
weapon_type                          0
weapon_details                      23
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [105]:
# NaN 값 처리하기 전에 밸류카운트로 어떤 값들이 있나 확인. NaN 값과 글자들을 통일 시킬 예정
df3['prior_signs_mental_health_issues'].value_counts()

Yes         58
Unclear     23
No          17
yes          6
TBD          5
Unknown      1
Unclear      1
Name: prior_signs_mental_health_issues, dtype: int64

In [106]:
# prior_signs_mental_health_issues의 NaN값 확인

df3['prior_signs_mental_health_issues'].isnull()

0       True
1       True
2       True
3       True
4       True
       ...
130    False
131    False
132    False
133    False
134    False
Name: prior_signs_mental_health_issues, Length: 135, dtype: bool

In [107]:
# prior_signs_mental_health_issues의 NaN값 확인

df3[df3['prior_signs_mental_health_issues'].isnull()]['prior_signs_mental_health_issues']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
9     NaN
10    NaN
13    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
21    NaN
22    NaN
26    NaN
28    NaN
30    NaN
31    NaN
32    NaN
34    NaN
35    NaN
Name: prior_signs_mental_health_issues, dtype: object

In [108]:
# 각 사건에 대한 자료출저들 과 값 변경

df3.loc[0,'prior_signs_mental_health_issues'] = 'TBD'
# https://edition.cnn.com/2022/11/14/us/university-of-virginia-shooting-suspect/index.html

df3.loc[1,'prior_signs_mental_health_issues'] = 'TBD'
#https://www.newsobserver.com/news/local/crime/article267301562.html

df3.loc[2,'prior_signs_mental_health_issues'] = 'TBD'
# https://en.wikipedia.org/wiki/Greenwood_Park_Mall_shooting

df3.loc[3,'prior_signs_mental_health_issues'] = 'yes'
# https://nypost.com/2022/07/07/robert-crimo-iii-told-cops-he-was-a-depressed-drug-user/

df3.loc[4,'prior_signs_mental_health_issues'] = 'TBD'
# https://qctimes.com/news/national/man-charged-in-alabama-church-shooting-fighting-mental-test/article_0c559c90-a214-5c08-9299-623100cbfe46.html

df3.loc[5,'prior_signs_mental_health_issues'] = 'TBD'
# https://www.dailymail.co.uk/news/article-10906051/Suspect-Maryland-concrete-plant-shooting-employee-working-day-shooting.html

In [109]:
# 몇개를 처리하다 보니 너무 시간이 오래걸리고 최신의 사건들이라 정보가 바로안나와서 TBD "To Be Decided" '곧 결정될 것'이라는 의미의 사건들이 많아서 NaN값을 TBD로 설정하기로 결정.

# df3.loc[df3['prior_signs_mental_health_issues'].isnull(),'prior_signs_mental_health_issues'] = df3[df3['prior_signs_mental_health_issues'].isnull()]['prior_signs_mental_health_issues'].fillna('TBD')

# 위의 입력 값이나 밑에 실행값이나 같음

df3['prior_signs_mental_health_issues'] = df3['prior_signs_mental_health_issues'].fillna('TBD')

In [110]:
# 처리 후, NaN값 있나 확인

df3[df3['prior_signs_mental_health_issues'].isnull()]['prior_signs_mental_health_issues']

Series([], Name: prior_signs_mental_health_issues, dtype: object)

In [111]:
# 값이 yes인 것들을 Yes로 통일

df3.loc[(df3['prior_signs_mental_health_issues'] == 'yes'), 'prior_signs_mental_health_issues'] = 'Yes'

In [112]:
# 값이 no인 것들을 No로 통일

df3.loc[(df3['prior_signs_mental_health_issues'] == 'no'), 'prior_signs_mental_health_issues'] = 'No'

In [113]:
# 값이 Unknown 인 것과 Unclear을 Unclear로 통일

df3.loc[(df3['prior_signs_mental_health_issues'] == 'Unknown'), 'prior_signs_mental_health_issues'] = 'Unclear'
df3.loc[(df3['prior_signs_mental_health_issues'] == 'Unclear'), 'prior_signs_mental_health_issues'] = 'Unclear'

In [114]:
# 밸류 카운트 값 확인

df3['prior_signs_mental_health_issues'].value_counts()

Yes         65
TBD         28
Unclear     24
No          17
Unclear      1
Name: prior_signs_mental_health_issues, dtype: int64

In [115]:
#변환이 안되서 찾아봤더니 공백이 있는 것을 확인.

df3['prior_signs_mental_health_issues'].unique()

array(['TBD', 'Yes', 'Unclear', 'No', 'Unclear '], dtype=object)

In [116]:
# 잘못 입력된 값 변경
df3.loc[(df3['prior_signs_mental_health_issues'] == 'Unclear '), 'prior_signs_mental_health_issues'] = 'Unclear'

In [117]:
# 밸류카운트

df3['prior_signs_mental_health_issues'].value_counts()

Yes        65
TBD        28
Unclear    25
No         17
Name: prior_signs_mental_health_issues, dtype: int64

In [118]:
#  mental_health_details 결측치 처리. 11월 20일 심재훈

In [119]:
# 전체 데이터에서 결측치가 있는 값을 찾아내기

df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details               38
weapons_obtained_legally            14
where_obtained                      41
weapon_type                          0
weapon_details                      23
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [120]:
# mental_health_details에서 결측치 값을 뽑아내본다.

df3[df3['mental_health_details'].isnull()]['mental_health_details']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
9     NaN
10    NaN
13    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
21    NaN
22    NaN
23    NaN
24    NaN
26    NaN
28    NaN
30    NaN
31    NaN
32    NaN
34    NaN
35    NaN
39    NaN
40    NaN
42    NaN
43    NaN
46    NaN
47    NaN
49    NaN
62    NaN
67    NaN
71    NaN
72    NaN
Name: mental_health_details, dtype: object

In [121]:
# 어떤 값들이 있나 확인. 불명확한 사실을 Unclear로 처리해 놨다는 사실을 확인.

df3['mental_health_details'].value_counts()

Unclear                                                                                                                                                                                                                                                                                                                                                                             6
previous threats and a mental health evaluation prompted by state police investigation in June 2021                                                                                                                                                                                                                                                                                 1
He had a criminal past, including a sexual assault conviction.                                                                                                                                                                                                                                                                                                                      1
Boys displayed unruly and aggressive behavior. They picked on kids and made threats about killing people.                                                                                                                                                                                                                                                                           1
Doctors testified that he was a paranoid schizophrenic who suffered from hallucinations                                                                                                                                                                                                                                                                                             1
                                                                                                                                                                                                                                                                                                                                                                                   ..
He was known as a solitary teen who regularly ditched class and had an interest in assault weapons; he had been admitted to UCLA's psychiatric ward for a brief period.                                                                                                                                                                                                             1
His mother told authorities her son had been acting strangely and needed a psychiatric evaluation.                                                                                                                                                                                                                                                                                  1
Had told Rhode Island police the prior month that he'd "heard voices"; had been undergoing mental health treatment with Veterans Affairs since August 2013.                                                                                                                                                                                                                         1
Lopez "had a long history of troubling behavior," according to the Washington Post, including a history of decieving others, problems in his personal life, and financial difficulties. However, officials found that Lopez exhibited no signals that he could be violent. In the year leading up to the attack, he sought treatment for medical and behavioral health ailments.    1
His second wife left him because he refused to seek psychological help. He had become increasingly isolated. One former student said he was "off his rocker."                                                                                                                                                                                                                       1
Name: mental_health_details, Length: 92, dtype: int64

In [122]:
# 어떤 값들이 있나 확인

df3['mental_health_details'].unique()

array([nan,
       'previous threats and a mental health evaluation prompted by state police investigation in June 2021',
       'Perpetrator had a history of depression, angry behavior and making people around him fearful; former intimate partners decribed him as being mentally unstable',
       'Perpetrator had been reported to police in 2020 by his mother as potentially suicidal; he was detained by authorities on a temporary mental health hold',
       'Brother described him as paranoid; multiple accounts of anger issues from others who knew him. Misdemeanor criminal record for a violent assault during his senior year in high school.',
       '"One friend of the family said the gunman had a long history of mental problems, trouble with the law and making racist comments," according to a report in the New York Times.',
       '(pending)',
       'Xaver was reported to have a lenghty history of expressing violent desires; an ex-girlfriend said she first met him at a psychiatric hospital in 2013.',
       'Per the LATimes: "Sheriff Geoff Dean said his department had had several interactions with Long, including a call to his home in April for a complaint of disturbing the peace. Deputies at the time said Long was irate and acting irrationally, Dean said. They called in mental health professionals to evaluate him, and they concluded he did not need to be taken into custody."',
       'Perez filed a "delusional" lawsuit in 2017 against CNBC and TD Ameritrade; the federal judge who threw out the case said Perez\'s allegations were "rambling, difficult to decpipher and borders on delusional."',
       'Reinking had a history of erratic behavior and run-ins with law enforcement in his home state of Illinois, including claims that he was being stalked and harassed by pop star Taylor Swift. In July 2017, he was arrested at the White House after breaching security in an effort to speak with President Trump, reportedly claiming his right to do so as “a sovereign citizen.”',
       'Wong had served in Afghanistan and had a history of PTSD.',
       'Cruz had a long history of behavioral problems and had spent time in mental health clinics.',
       'Kelley had a history of domestic violence, including a court martial and conviction stemming from assaulting his wife and child; he also had a history of cruelty to animals and of stalking and harassing ex-girlfriends, including an underage girl. He reportedly briefly escaped from a mental health facility in 2012.',
       "Perpetrator's history unclear. In 1969 Paddock's father was classified by the FBI as a dangerous psychopath with suicidal tendencies; psychopathy can be heritable (see Mother Jones sourcing). ",
       'Lam had a history of domestic, work conflict',
       'Hartless had a violent criminal history; his former girlfriend had submitted a letter in court recently stating that he had "a severe mental disorder."',
       'Among other signs, Santiago had gone to a FBI office in Anchorage and complained that his mind was being controlled by the CIA.',
       'According to the Cetin\'s stepfather he had "mental health issues"; court records showed that he suffered from anxiety and depression. ',
       'Unclear',
       'The judge in the case has not publicly released Dear\'s medical and mental health records. As of April 5, 2016, Dear was undergoing a competency evaluation. Dear had a history of disputes with his relatives and neighbors. At a hearing in December 2015, he said, "I am a warrior for the babies."',
       'Prior to the rampage, Harpham wrote an "incoherent" blog and rambled "nonsensically" in a YouTube video about mind control techniques and God, according to the Denver Post. He had a history of drug and alcohol abuse. ',
       "Harper-Mercer's mother said in multiple online postings that he had Asperger's syndrome. Harper-Mercer graduated from the Switzer Learning Center, a school for students with special needs, emotional difficulties, autism and Asperger's syndrome.",
       'Abdulazeez "had suffered for years from depression and possibly from bipolar disorder," according to a representative of the family. (NYT, July 20 2015)',
       'While serving in the Air Force, he went to an emergency walk-in clinic because of concerns over his mood swings, and had either sought or been ordered to behavioral health interventions, according to Fox 6 Now. In a 2014 risk assessment with a psychologist at an outpatient clinic in Appleton, Valencia del Toro recalled thinking previously: "If I\'m gonna take myself out, I might as well take other people with me." The police report obtained by Fox 6 says that Valencia del Toro had a history of depression, suicidal and occassionally homicidal thoughts, and alcoholism. He was intoxicated on the day of the shooting.',
       'Fryberg was well-liked and allegedly happy, but was also upset about a girl and had posted emotional social media messages. No definitive signs of mental health problems.',
       'Rodger was never hospitalized due to mental illness, but had a long history of mental health issues dating back to his childhood, and received treatment from multiple counselors leading up to his rampage. According to The Independent, Rodger had considered suicide but had no history of violence. Just before his rampage, he sent a 137-page manifesto to multiple people.',
       'Lopez "had a long history of troubling behavior," according to the Washington Post, including a history of decieving others, problems in his personal life, and financial difficulties. However, officials found that Lopez exhibited no signals that he could be violent. In the year leading up to the attack, he sought treatment for medical and behavioral health ailments.',
       'Had told Rhode Island police the prior month that he\'d "heard voices"; had been undergoing mental health treatment with Veterans Affairs since August 2013.',
       'His mother told authorities her son had been acting strangely and needed a psychiatric evaluation.',
       "He was known as a solitary teen who regularly ditched class and had an interest in assault weapons; he had been admitted to UCLA's psychiatric ward for a brief period.",
       'Lanza had a history of serious mental health problems that were known to his family and others, as detailed in a post-massacre investigation by Connecticut authorities.',
       'His family worried about his "paranoia and delusions" for at least two years prior, and tried to get him to seek treatment.',
       'His Army friends once broke into his apartment, fearing he\'d commit suicide in the \'90s. A psychiatric nurse who lived downstairs from Page said it was "obvious" he had a mental illness.',
       'He saw at least three mental health professionals before dropping out of his university.',
       'His family said he was mentally ill',
       'A former instructor at Oikos described him as "mentally unstable" and "paranoid."',
       'His sister worried about his homicidal tendencies; she said his mental health had been deteriorating and that he had threatened to commit suicide with his gun.',
       'He suffered from bipolar disorder, mood swings, and PTSD. After an assault on his elderly stepfather, he was sentenced in 2008 to a year of anger management therapy.',
       'He was diagnosed with paranoid schizophrenia as a teenager and feared demons were out to get him.',
       'His symptoms pointed to various possible mental illness diagnoses, such as schizophrenia and delusional disorder. He also experimented with pot and hallucinogens.',
       'He apparently was driven over the edge by unaddressed, ongoing racism against him at work',
       'He had a history of erratic, bizarre behavior. He once asked his family to get naked for 5 minutes on Sunday; he said he thought the world would end and that he was Jesus.',
       "Medical officials at Walter Reed Army Medical Center and the Uniformed Services University of the Health Sciences raised concerns prior to the shooting regarding Hasan's aloof and erratic behavior and extremist Islamic views.",
       'He apparently harbored growing paranoia toward cops. He also sent a delusional letter to a local TV station right before the shooting.',
       'His estranged wife told her workplace that her husband had an "unstable mental state or (was) mentally ill."',
       'He called his girlfriend two hours before the shooting to say he was going to kill his boss.',
       'He had a long history of mental health struggles; after high school, his parents placed him at a psychiatric treatment center. He told friends he left the Army after six months due to a psychological discharge. ',
       'He was known for histrionics and disruptions at city council meetings. His mounting debt was a stressor.',
       'He had been treated in the past for depression and ADHD. ',
       "The families of victims filed a wrongful death lawsuit against the county arguing that the police department should have evaluated the gunman's mental health before hiring him.",
       'A district court ruled Cho was "an imminent danger" to himself and others as a result of mental illness two years earlier, and directed Cho to seek treatment. ',
       'According to one relative, he was violent and had the mental capacity of a child. (But accounts from others did not indicate this about the shooter.)',
       "He told his wife that he'd molested two young relatives 20 years ago. ",
       'Police were unable to find any record that he had been treated for mental illness or was on psychiatric medication.',
       'She was placed on retirement disability for psychological reasons. Fellow employees described her behavior as increasingly bizarre. She believed the Postal Service employees were conspiring against her.',
       'He voluntarily visited a a psychiatric ward. He was hospitalized at least once for suicidal tendencies and was taking Prozac.',
       'Neighbors said he suffered from depression and had a drinking problem.',
       'He was discharged from the military because he was a paranoid schizophrenic.',
       'His cousin said he was depressed and "going through a lot of things."',
       'He had a criminal past, including a sexual assault conviction.',
       'Psychiatrist guessed he had schizophrenia, but McDermott had researched how to fake a mental illness on the internet. Defense lawyer described history of suicide attempts and mental illness dating back to teen years. Jury rejected his insanity defense. ',
       'His brother called him "unbalanced" and mentally ill.',
       ' A psychiatrist, testifying for the prosecution,said he suffered from schizophrenia.',
       'His siblings decribed him as a paranoid schizophrenic. ',
       'In letters, he details his deep depression and downward spiral. ',
       'Harris was an alleged psychopath; Klebold was depressed and suicidal.',
       'Doctors testified that he was a paranoid schizophrenic who suffered from hallucinations',
       'Boys displayed unruly and aggressive behavior. They picked on kids and made threats about killing people. ',
       'He had been hospitalized for psychiatric reasons and had a history of depression',
       'He was disgruntled after being fired. ',
       'An ex-con, he had been freed from prison, although he displayed violent tendencies.',
       'Co-workers complained about his threats and verbal abuse. His supervisors asked him to get a psychiatric evaluation. He lost his job, which relatives said drove his depression.',
       "He was likely angry because he was given an assignment at work he didn't like. But acquaintances didn't know why he'd come back and kill.",
       'He was repeatedly diagnosed with emotional problems during his two years of service.',
       'While he was in prison awaiting trial, he started acting bizarre by stripping naked and playing with his feces, apparently to avoid the death penalty. A state doctor testified that Dunlap was was faking his mental illness. ',
       'Psychiatrists and others said he suffered from racial paranoia and was obsessed with nonexistent conspiracies. His landlord said he had "delusions of grandeur."',
       'He had an abusive father, who committed suicide.',
       'He was down on his luck because of failed business decisions. One acquaintance said, "He was the least likely guy you can imagine doing something like that."  His ex-wife said he "hated violence."',
       "The day before the shooting, he told child-support collection office workers that he was considering suicide. He had been convicted of felonious assault for pointing a revolver at police officers responding to a domestic violence report at this girlfriend's apartment. ",
       'He suffered violent physical abuse as a child. He claimed a teacher had sexually abused him, but the truth of that allegation was contested. ',
       'Police revoked his CCW permit after determining he was mentally unstable.',
       'He was described as darkly disturbed and isolated.',
       'Acquaintances described him as troubled, unstable, combative, and misogynistic. He made convenience store employees "nervous."',
       'Police speculated he had a "grudge" against the people he killed. ',
       'Prior to the shooting, he had voluntarily checked into hospitals for mental problems at least twice and attempted suicide three times. ',
       'He told a mental health professional he was "struggling to resist actions on thoughts which are destructive in nature." He also suffered from alcoholism. ',
       'He stalked and harassed his colleague Laura Black for four years until she was granted a temporary restraining order aginst him. Before he was fired for his bizarre behavior, he was ordered to undergo psychological counseling. ',
       'He suffered from paranoid delusions. A judge found that he suffered from "extreme mental illness."',
       "He was worried he had inherited mental problems and rebuffed a pastor's suggestion he seek psychiatric counseling. His family members denied he had a history of mental illness.",
       'The day before the shooting, he tried to make an appointment at a mental health clinic. ',
       'During his last meal with his wife, he confessed he was depressed and had visited psychiatric hospitals in Belgium.',
       'His second wife left him because he refused to seek psychological help. He had become increasingly isolated. One former student said he was "off his rocker."'],
      dtype=object)

In [123]:
# 값이 Unclear인 값들을 확인해본다.

df3.loc[(df3['mental_health_details'] == 'Unclear'), 'mental_health_details']

52    Unclear
53    Unclear
54    Unclear
55    Unclear
56    Unclear
57    Unclear
Name: mental_health_details, dtype: object

In [124]:
# 결측치를 Unclaer로 채워준다.

df3['mental_health_details'] = df3['mental_health_details'].fillna('Unclear')

In [125]:
# mental_health_details에서 결측치가 있는 값을 뽑아내본다.

df3[df3['mental_health_details'].isnull()]['mental_health_details']

Series([], Name: mental_health_details, dtype: object)

In [126]:
#  weapons_obtained_legally 결측치 처리. 11월 20일 심재훈

In [127]:
# 결측치 확인

df3[df3['weapons_obtained_legally'].isnull()]['weapons_obtained_legally']

0     NaN
1     NaN
5     NaN
9     NaN
10    NaN
11    NaN
13    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
28    NaN
Name: weapons_obtained_legally, dtype: object

In [128]:
# 밸류카운트로 확인하였지만 너무 많은 값들이 있는 것을 확인. 위의 결측치를 Unknown 값으로 변경하기로 결정.

df3['weapons_obtained_legally'].value_counts()

Yes                                                                                                                                    80
No                                                                                                                                     16
yes                                                                                                                                     7
TBD                                                                                                                                     7
Unknown                                                                                                                                 6
\nYes                                                                                                                                   2
Kelley passed federal criminal background checks; the US Air Force failed to provide information on his criminal history to the FBI     1
Yes ("some of the weapons were purchased legally and some of them may not have been")                                                   1
Yes                                                                                                                                     1
Name: weapons_obtained_legally, dtype: int64

In [129]:
# 결측치를 Unknown으로 채워준다.

df3['weapons_obtained_legally'] = df3['weapons_obtained_legally'].fillna('Unknown')

In [130]:
# 결측치 확인

df3[df3['weapons_obtained_legally'].isnull()]['weapons_obtained_legally']

Series([], Name: weapons_obtained_legally, dtype: object)

In [131]:
# 괄호안에 명시되어 있는 정확한 값들을 확인하여 통일 해줄 함수를 작성해준다.

# TBD "To Be Decided" '곧 결정될 것'이라는 뜻
# Kell~ 는 Kelley는 연방 범죄 신원 조회를 통과했습니다. 미 공군은 그의 범죄 기록에 대한 정보를 FBI에 제공하지 못했습니다로 해석되니 Unknown으로 묶어준다.
# some ~는 무기 중 일부는 합법적으로 구매했으며 일부는 구매하지 않았을 수 있습니다.라는 뜻으로 그냥 Yes로 분류해준다.


df3['weapons_obtained_legally'].unique()

array(['Unknown', 'yes', 'Yes', 'No', 'TBD',
       'Kelley passed federal criminal background checks; the US Air Force failed to provide information on his criminal history to the FBI',
       '\nYes',
       'Yes ("some of the weapons were purchased legally and some of them may not have been")',
       'Yes '], dtype=object)

In [132]:
# 기존의 값들을 통일시켜줄 함수작성

def legally(legally) :
    legally_dict = {'yes':'Yes',
                    'Yes':'Yes',
                   '\nYes':'Yes',
                   'Yes ':'Yes',
                   'Yes ("some of the weapons were purchased legally and some of them may not have been")':'Yes',
                   'Kelley passed federal criminal background checks; the US Air Force failed to provide information on his criminal history to the FBI':'Unknown',
                   'No':'No',
                   'TBD':'TBD',
                   'Unknown':'Unknown'
                   }
    return legally_dict.get(legally)

In [133]:
# 컬럼에 함수적용

df3['weapons_obtained_legally'] = df3['weapons_obtained_legally'].apply(legally)

In [134]:
# 밸류카운트로 내용 전처리 확인

df3['weapons_obtained_legally'].value_counts()

Yes        91
Unknown    21
No         16
TBD         7
Name: weapons_obtained_legally, dtype: int64

In [135]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                      41
weapon_type                          0
weapon_details                      23
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [136]:
#  weapons_obtained_legally 결측치 처리. 11월 20일 심재훈

In [137]:
# 결측치 확인

df3[df3['where_obtained'].isnull()]['where_obtained']

0     NaN
1     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
31    NaN
32    NaN
34    NaN
42    NaN
46    NaN
47    NaN
48    NaN
49    NaN
50    NaN
51    NaN
52    NaN
55    NaN
56    NaN
65    NaN
67    NaN
Name: where_obtained, dtype: object

In [138]:
# 어떤 값들이 얼마나 들어있는지 확인. 결측치를 Unknown으로 분류해주고, Unknown이나 Unclear나 같은 의미이니 통일시켜 준다.

df3['where_obtained'].value_counts()

Unknown                                  15
Unclear                                   4
TBD                                       3
Purchased from an individual              2
in Greenwood                              1
                                         ..
Gun dealer in East Windsor, Conn.         1
Stolen from an individual in Seattle.     1
Guns Galore in Kileen, Texas              1
Gander Mountain in Johnson City, N.Y.     1
Garcia Gun Center in Hialeah, Fla.        1
Name: where_obtained, Length: 74, dtype: int64

In [139]:
# 고유값 확인

df3['where_obtained'].unique()

array([nan, 'in Greenwood',
       'legally purchased by the shooter in the "greater Chicago area" per authorities',
       'Nevada, on July 9', 'A gun store in Simi Valley',
       '(Unclear; investigators confirmed he owned 10 guns in total, all purchased and possessed legally, and had a handgun license)',
       'A local gun store', "Father's weapons", 'Family member', 'TBD',
       'A Florida pawn shop',
       'Purchased in April 2016 from an Academy Sports & Outdoors store in San Antonio',
       'Unclear', 'Two gun shops in Nevada',
       'Unclear; the firearm was stolen in Utah. A second handgun Lam had (also stolen) was unused in the attack.',
       'online and or gun show',
       'Shooting center in Port St. Lucie, Florida',
       'The suspects purchased their handguns in the United States; the assault rifles were purchased by a third party.',
       'From the home he shared with his mother. All were legally obtained by either Harper/Mercer or family members.',
       'On the internet, via Armslist.com',
       "Shooter's Choice gun store in West Columbia, South Carolina",
       "Gun was his father's.", 'Local gun store in Killeen, Guns Galore',
       'Sharpshooters Small Arms Range', 'Florida Gun Center',
       'Assembled a rifle out of component parts.', 'Unknown',
       "Frank's Guns in Marcy, NY", 'Stolen from mother',
       'Gander Mountain stores in Thornton and Aurora, Colo.; Bass Pro Shop in Denver, Colo.; BulkAmmo.com',
       "Bull's Eye Shooter Supply in Tacoma, Wash.",
       'Bullseye in Castro Valley, Calif.',
       'Purchased from an individual',
       "Sportsmen's Warehouse in Tucson, Ariz.",
       'Gun dealer in East Windsor, Conn.',
       'Stolen from an individual in Seattle.',
       'Guns Galore in Kileen, Texas',
       'Gander Mountain in Johnson City, N.Y.',
       'Local sporting goods stores and individuals',
       'Online and gun retailers in Champaign, Ill. ',
       'Taken in burglary and from fallen police officer',
       'Stolen from grandfather',
       "Issued by Forest County Sheriff's Department",
       'Purchased variously online and from Roanoke Firearms in Roanoke, Va.',
       "Purchased variously from Sportsman's Fast Cash in West Valley City, Utah and individuals ",
       'Local stores in Nickel Mines, Penn. ',
       'Various sporting goods stores in Kalispell, Mont.',
       'Pawn shops in Grants and Gallup, N.M.',
       'Glock and Remington stolen from grandfather',
       'Gun dealer in Waukesha, Wis.', 'Received as a gift from mother',
       'Some purchased from Pepper Sports in Glen Ellyn, Ill. ',
       "One purchased from Big E's in Tampa, Fla.",
       'Hunting Supplies of Hawaii (The Armory) in Honolulu, Hawaii',
       "Trader's Village flea market in Grand Prairie, Texas",
       'Glock purchased from gun store in Warner Robins, Ga. ',
       'Purchased variously at Tanner Gun Show in Denver, Colo. and from an individual',
       'Purchased variously from friend and father, and stolen from father',
       'Stolen from grandfather and father',
       'B&B Gun Sales in Orange County, Calif.',
       'Gun dealer in Spokane, Wash.',
       "Turner's Outdoorsman in Signal Hill, Calif. ",
       'Super Pawn and Pacific Tactical Weapons, both in Las Vegas, Nev.',
       'Mumford Sports in Litchfield, Ohio', 'Local gun retailer',
       'Local gun store', 'Fin & Feather in Iowa City, Iowa',
       "Mike's Gun Shop in Henderson, Nev.",
       "AK-47 purchased from Tilford's Gun Sales in Louisville, Ky. ",
       'Sandy Trading Post in Sandy, Ore.; Hunter Loan and Jewelry Co. in Stockton, Calif.',
       'Various sporting goods and gun stores in Northern California',
       'Gun store in Norwood, Ohio; The Oaks Trading Post in Melbourne, Fla.',
       'Issued by Oklahoma National Guard, where Sherrill served, for target competition  ',
       'Hines Boulevard Pawn Shop in Dallas, Texas',
       'Garcia Gun Center in Hialeah, Fla.'], dtype=object)

In [140]:
#결측치를 언노운으로 채워준다.

df3['where_obtained'] = df3['where_obtained'].fillna('Unknown')

In [141]:
# 언클리어를 언노운으로 합쳐준다.

df3.loc[(df3['where_obtained'] == 'Unclear'), 'where_obtained'] = 'Unknown'

In [142]:
# 밸류카운트

df3['where_obtained'].value_counts()

Unknown                                         60
TBD                                              3
Purchased from an individual                     2
Issued by Forest County Sheriff's Department     1
Gun dealer in Waukesha, Wis.                     1
                                                ..
Assembled a rifle out of component parts.        1
Florida Gun Center                               1
Sharpshooters Small Arms Range                   1
Local gun store in Killeen, Guns Galore          1
Garcia Gun Center in Hialeah, Fla.               1
Name: where_obtained, Length: 73, dtype: int64

In [143]:
# 결측치 확인

df3[df3['where_obtained'].isnull()]['where_obtained']

Series([], Name: where_obtained, dtype: object)

In [144]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                       0
weapon_type                          0
weapon_details                      23
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [145]:
#  weapon_details 결측치 처리. 11월 20일 심재훈

In [146]:
# 결측치 확인

df3[df3['weapon_details'].isnull()]['weapon_details']

0     NaN
1     NaN
4     NaN
5     NaN
7     NaN
9     NaN
11    NaN
12    NaN
13    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
26    NaN
35    NaN
37    NaN
39    NaN
42    NaN
46    NaN
47    NaN
48    NaN
Name: weapon_details, dtype: object

In [147]:
# 어떤 값들이 얼마나 들어있는지 확인. > 기타로 분류되어 있는 값이 없어서 이것은 결측치를 기타로 통으로 묶거나 하나하나조사를 해야겠다고 생각.
# 후자의 방법을 택함.

df3['weapon_details'].value_counts()

.45-caliber semiautomatic handgun                                                                                                                                                      2
9mm semiautomatic handgun                                                                                                                                                              2
AK-47-style rifle, per authorities                                                                                                                                                     2
9mm handgun                                                                                                                                                                            2
AR-15                                                                                                                                                                                  2
                                                                                                                                                                                      ..
9 mm Glock pistol, .40 caliber Smith & Wesson, .40 caliber Taurus pistol, .556 caliber Del-Ton; (ammo details unclear)                                                                 1
AR-15 rifle, a 9 mm pistol, and a .357 revolver                                                                                                                                        1
Reportedly an AK-47 style semiautomatic rifle and others. Authorities had not released details on Dear's weapons as of April 2016.                                                     1
Two semiautomatic AR-15-style rifles—one a DPMS A-15, the other a Smith & Wesson M&P15, both with .223 calibre ammunition. Two 9mm semiautomatic handguns. High capacity magazines.    1
Mossberg 500 Persuader pump-action shotgun with pistol grip                                                                                                                            1
Name: weapon_details, Length: 107, dtype: int64

In [148]:
# 자료 조사하기 편하게 결측치를 case명으로 분류

df3[df3['weapon_details'].isnull()]['case']

0            University of Virginia shooting
1                     Raleigh spree shooting
4             Church potluck dinner shooting
5                  Concrete company shooting
7            Robb Elementary School massacre
9          Sacramento County church shooting
11                     San Jose VTA shooting
12                  FedEx warehouse shooting
13            Orange office complex shooting
15          Atlanta massage parlor shootings
16    Springfield convenience store shooting
17                     Molson Coors shooting
18        Jersey City kosher market shooting
19             Pensacola Naval base shooting
20             Odessa-Midland shooting spree
26           Pennsylvania hotel bar shooting
35             Santa Fe High School shooting
37         Yountville veterans home shooting
39             Pennsylvania carwash shooting
42       Walmart shooting in suburban Denver
46         Pennsylvania supermarket shooting
47      Florida awning manufacturer shooting
48          Rural Ohio nursing home shooting
Name: case, dtype: object

In [149]:
# 결측값 및 자료 출처

df3.loc[0,'weapon_details'] = 'store owner Marlon Dance said Jones had purchased two firearms in 2022 from his story, including a 9mm pistol in July and a rifle in February'
# https://www.nbc12.com/2022/11/17/uva-shooting-suspect-purchased-2-guns-colonial-heights-store-earlier-this-year/

df3.loc[1,'weapon_details'] = 'The teen suspect in last weeks mass shooting was armed with a shotgun, a handgun, and a hunting knife.'
# https://abc11.com/raleigh-nc-shooting-active-shooter-today-austin-thompson/12349829/

df3.loc[4,'weapon_details'] = 'pulled out a handgun'
# https://www.usnews.com/news/us/articles/2022-06-17/alabama-church-shooting-kills-2-wounds-1-suspect-held

In [150]:
# 추가한 결측 값 확인.

df3.loc[0:50,'weapon_details']

0     store owner Marlon Dance said Jones had purcha...
1     The teen suspect in last weeks mass shooting w...
2                                  Sig Sauer M400 rifle
3     AR-15 style rifle, possibly modified for rapid...
4                                  pulled out a handgun
5                                                   NaN
6                                     AR-15 style rifle
7                                                   NaN
8                  Bushmaster XM-15 semiautomatic rifle
9                                                   NaN
10                                 Sig Sauer 9mm pistol
11                                                  NaN
12                                                  NaN
13                                                  NaN
14    Ruger AR-556; weapon was purchased six days be...
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                                  NaN
19                                                  NaN
20                                                  NaN
21    AR-15-style rifle, with a 100-round capacity a...
22                   AK-47-style rifle, per authorities
23                   AK-47-style rifle, per authorities
24    .45-caliber handguns; noise suppressor (silenc...
25    Smith & Wesson handgun, with a green sighting ...
26                                                  NaN
27                                         9 mm handgun
28                                          9mm handgun
29        Glock 21, .45 caliber; high-capacity magazine
30                                AR-15; Glock .357 (3)
31                                           Glock 9 mm
32      Smith & Wesson Model 500 (.50-caliber revolver)
33                                          9mm handgun
34                         12-gauge pump-action shotgun
35                                                  NaN
36                                                AR-15
37                                                  NaN
38                                                AR-15
39                                                  NaN
40                        Two illegally modified rifles
41    Ruger AR-556; Kelley also possessed semiautoma...
42                                                  NaN
43                           .380-caliber; make unclear
44    AR-15-style and AK-47-style rifles and "a larg...
45    MAC-10-style “assault pistol”; 30-round magazi...
46                                                  NaN
47                                                  NaN
48                                                  NaN
49                                        .357 revolver
50                   Walther 9mm semi-automatic pistol[
Name: weapon_details, dtype: object

In [151]:
# 조사를 하다보니 최근의 사건들이라서 정확한 총기류를 분류하기 힘들다는 것을 알았다. 
# 때문에 위에 3개 사건들을 제외한 모든 결측치를 not clearly classified. 로 분류하기로 결정함.
# 결측값을 채워준다.

df3['weapon_details'] = df3['weapon_details'].fillna('not clearly classified.')

In [152]:
# 결측치 확인

df3[df3['weapon_details'].isnull()]['weapon_details']

Series([], Name: weapon_details, dtype: object)

In [153]:
# 추가한 결측 값 확인.

df3.loc[0:50,'weapon_details']

0     store owner Marlon Dance said Jones had purcha...
1     The teen suspect in last weeks mass shooting w...
2                                  Sig Sauer M400 rifle
3     AR-15 style rifle, possibly modified for rapid...
4                                  pulled out a handgun
5                               not clearly classified.
6                                     AR-15 style rifle
7                               not clearly classified.
8                  Bushmaster XM-15 semiautomatic rifle
9                               not clearly classified.
10                                 Sig Sauer 9mm pistol
11                              not clearly classified.
12                              not clearly classified.
13                              not clearly classified.
14    Ruger AR-556; weapon was purchased six days be...
15                              not clearly classified.
16                              not clearly classified.
17                              not clearly classified.
18                              not clearly classified.
19                              not clearly classified.
20                              not clearly classified.
21    AR-15-style rifle, with a 100-round capacity a...
22                   AK-47-style rifle, per authorities
23                   AK-47-style rifle, per authorities
24    .45-caliber handguns; noise suppressor (silenc...
25    Smith & Wesson handgun, with a green sighting ...
26                              not clearly classified.
27                                         9 mm handgun
28                                          9mm handgun
29        Glock 21, .45 caliber; high-capacity magazine
30                                AR-15; Glock .357 (3)
31                                           Glock 9 mm
32      Smith & Wesson Model 500 (.50-caliber revolver)
33                                          9mm handgun
34                         12-gauge pump-action shotgun
35                              not clearly classified.
36                                                AR-15
37                              not clearly classified.
38                                                AR-15
39                              not clearly classified.
40                        Two illegally modified rifles
41    Ruger AR-556; Kelley also possessed semiautoma...
42                              not clearly classified.
43                           .380-caliber; make unclear
44    AR-15-style and AK-47-style rifles and "a larg...
45    MAC-10-style “assault pistol”; 30-round magazi...
46                              not clearly classified.
47                              not clearly classified.
48                              not clearly classified.
49                                        .357 revolver
50                   Walther 9mm semi-automatic pistol[
Name: weapon_details, dtype: object

In [154]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                       0
weapon_type                          0
weapon_details                       0
race                                12
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [155]:
# race 결측치 처리. 11월 20일 심재훈

In [156]:
#결측값 확인

df3[df3['race'].isnull()]['race']

5     NaN
9     NaN
10    NaN
11    NaN
13    NaN
14    NaN
16    NaN
19    NaN
23    NaN
29    NaN
47    NaN
51    NaN
Name: race, dtype: object

In [157]:
# 밸류 카운트

df3['race'].value_counts()

white              41
White              30
Black              14
Latino             11
black               9
Asian               8
Other               5
Native American     3
White               1
unclear             1
Name: race, dtype: int64

In [158]:
# 특정 값 확인

df3['race'].unique()

array(['Black', 'White', nan, 'Latino', 'Asian', 'Other', 'White ',
       'Native American', 'white', 'black', 'unclear'], dtype=object)

In [159]:
# 결측값들을 unclear로 분류해준다.

df3['race'] = df3['race'].fillna('unclear')

In [160]:
df3[df3['race'].isnull()]['race']

Series([], Name: race, dtype: object)

In [161]:
df3['race'].unique()

array(['Black', 'White', 'unclear', 'Latino', 'Asian', 'Other', 'White ',
       'Native American', 'white', 'black'], dtype=object)

In [162]:
# 유니크 값들을 통일

df3.loc[(df3['race'] == 'unclear'), 'race'] = 'Unclear'
df3.loc[(df3['race'] == 'White '), 'race'] = 'White'
df3.loc[(df3['race'] == 'white'), 'race'] = 'White'
df3.loc[(df3['race'] == 'black'), 'race'] = 'Black'

In [163]:
# 밸류 카운트

df3['race'].value_counts()

White              72
Black              23
Unclear            13
Latino             11
Asian               8
Other               5
Native American     3
Name: race, dtype: int64

In [164]:
# 결측치를 확인

df3[df3['race'].isnull()]['race']

Series([], Name: race, dtype: object)

In [165]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                       0
weapon_type                          0
weapon_details                       0
race                                 0
gender                               0
sources                              0
mental_health_sources               51
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [166]:
# mental_health_sources 결측치 처리. 11월 20일 심재훈

In [167]:
# 결측값 확인

df3[df3['mental_health_sources'].isnull()]['mental_health_sources']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
9     NaN
10    NaN
13    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
28    NaN
30    NaN
31    NaN
32    NaN
33    NaN
34    NaN
35    NaN
39    NaN
40    NaN
42    NaN
43    NaN
46    NaN
47    NaN
49    NaN
52    NaN
53    NaN
54    NaN
55    NaN
56    NaN
57    NaN
58    NaN
59    NaN
61    NaN
62    NaN
63    NaN
65    NaN
66    NaN
67    NaN
71    NaN
Name: mental_health_sources, dtype: object

In [168]:
# 밸류 카운트

df3['mental_health_sources'].value_counts()

https://www.nytimes.com/2022/05/15/nyregion/gunman-buffalo-shooting-suspect.html                                                    1
http://www.sptimes.com/News/123000/news_pf/TampaBay/A_year_later__the_str.shtml                                                     1
http://articles.latimes.com/1997/dec/20/news/mn-431                                                                                 1
http://www.nytimes.com/2000/04/11/us/hole-in-gun-control-law-lets-mentally-ill-through.html?pagewanted=all&src=pm                   1
http://www.nytimes.com/1998/03/29/us/from-wild-talk-and-friendship-to-five-deaths-in-a-schoolyard.html?sec=&spon=&pagewanted=all    1
                                                                                                                                   ..
http://usnews.nbcnews.com/_news/2012/05/30/11959312-six-killed-in-seattle-shootings-including-suspect?lite                          1
http://www.cbsnews.com/8301-201_162-57497820/james-holmes-saw-three-mental-health-professionals-before-shooting/                    1
http://www.jsonline.com/news/milwaukee/friend-of-page-feared-what-he-might-do-426edmg-165668826.html                                1
http://www.startribune.com/local/171774461.html?refer=y                                                                             1
http://news.google.com/newspapers?id=uuYLAAAAIBAJ&sjid=C1kDAAAAIBAJ&pg=4879,1435085&dq=carl+robert+brown                            1
Name: mental_health_sources, Length: 84, dtype: int64

In [169]:
# 유니크 값 확인

df3['mental_health_sources'].unique()

array([nan,
       'https://www.nytimes.com/2022/05/15/nyregion/gunman-buffalo-shooting-suspect.html',
       'https://www.nytimes.com/2021/05/26/us/what-happened-in-san-jose-shooting.html?referringSource=articleShare',
       'https://www.nytimes.com/2021/04/19/us/indianapolis-shooting-red-flag-law.html',
       'https://www.thedailybeast.com/boulder-colorado-cops-identify-king-soopers-supermarket-massacre-suspect-as-ahmad-alissa',
       'https://www.nytimes.com/2019/09/02/us/texas-gunman-odessa-midland.html',
       'https://wsbt.com/news/local/classmate-says-florida-bank-shooter-who-allegedly-killed-5-attended-bremen-high-school; https://www.washingtonpost.com/nation/2019/01/23/several-people-shot-after-gunman-barricades-himself-florida-bank-authorities-say/',
       'http://www.latimes.com/local/lanow/la-me-ln-thousand-oaks-20181107-story.html',
       'https://www.buzzfeed.com/briannasacks/this-is-what-we-know-about-the-suspected-waffle-house-gunman?utm_term=.ilj2Knad6#.lklzyb3vj',
       'https://www.cnn.com/2018/03/10/us/california-veterans-home-shooting/index.html',
       'https://www.nytimes.com/2018/02/15/us/nikolas-cruz-florida-shooting.html',
       'http://www.expressnews.com/news/local/article/Suspected-gunman-Devin-Patrick-Kelley-lived-near-12334186.php; http://www.denverpost.com/2017/11/06/texas-shooting-devin-patrick-kelley-colorado-arrest/; https://www.nbcnews.com/storyline/texas-church-shooting/who-devin-kelley-alleged-texas-church-shooter-n817806; https://www.click2houston.com/news/sutherland-springs-church-shooter-escaped-mental-health-facility-months-after-attack-on-wife-child',
       'https://www.nytimes.com/2017/10/13/us/stephen-paddock-father-vegas.html; http://www.motherjones.com/crime-justice/2017/10/the-las-vegas-shooter-didnt-just-snap-they-never-do/',
       'http://www.ktvu.com/news/ktvu-local-news/261771610-story; https://twitter.com/LauraGarciaCann/status/875072768471117824; http://heavy.com/news/2017/06/jimmy-lam-ups-san-francisco-shooting-suspect/; http://heavy.com/news/2017/06/jimmy-lam-ups-san-francisco-shooting-suspect/',
       'http://www.cbsnews.com/news/64-guns-seized-from-home-of-killer-in-ohio-nursing-home-shooting/',
       'http://www.nytimes.com/2017/01/07/us/esteban-santiago-fort-lauderdale-airport-shooting-.html?_r=0',
       'http://www.nbcnews.com/news/us-news/arcan-cetin-accused-cascade-mall-shooter-charged-five-counts-murder-n654586',
       'http://www.latimes.com/nation/nationnow/la-na-nn-chris-harper-mercer-oregon-shooting-20151002-htmlstory.html',
       'http://www.newyorker.com/science/maria-konnikova/almost-link-mental-health-gun-violence',
       'http://bigstory.ap.org/article/13-killed-washington-navy-yard-shooting-rampage',
       'http://www.miamiherald.com/2013/08/03/v-print/3539629/hialeah-killer-showed-signs-of.html',
       'http://www.cbsnews.com/8301-504083_162-57589327-504083/john-zawahri-suspected-gunman-in-deadly-santa-monica-shooting-left-farewell-note-police-say/   http://www.latimes.com/news/local/la-me-0611-santa-monica-shooting-20130611,0,1490078.story',
       'http://poststar.com/news/local/state-and-regional/cops-kill-suspect-in-deadly-mohawk-valley-shooting-rampage/article_15260208-8bf5-11e2-b2d9-0019bb2963f4.html',
       'http://usnews.nbcnews.com/_news/2012/12/14/15911025-authorities-id-gunman-who-killed-27-in-elementary-school-massacre?lite; http://articles.washingtonpost.com/2012-12-14/local/35846977_1_law-enforcement-lanza-brothers-kid',
       'http://www.startribune.com/local/171774461.html?refer=y',
       'http://www.jsonline.com/news/milwaukee/friend-of-page-feared-what-he-might-do-426edmg-165668826.html',
       'http://www.cbsnews.com/8301-201_162-57497820/james-holmes-saw-three-mental-health-professionals-before-shooting/',
       'http://usnews.nbcnews.com/_news/2012/05/30/11959312-six-killed-in-seattle-shootings-including-suspect?lite',
       'http://berkeley.patch.com/articles/one-l-goh-showed-violent-tendencies-before-the-oikos-university-shooting-oikos-university-shooting; http://blog.sfgate.com/eguillermo/2012/04/05/something-still-doesnt-compute-in-the-one-goh-nightmare/',
       'http://www.gwinnettdailypost.com/news/2012/feb/23/police-id-4-victims-shooter-in-spa-killing/',
       'http://laist.com/2011/10/13/seal_beach_shooter_suffered_from_ptsd.php',
       'http://www.huffingtonpost.com/2011/11/03/eduardo-sencion-ihop-shooter_n_1073677.html',
       'http://www.time.com/time/magazine/article/0,9171,2042358,00.html',
       'http://www.cbsnews.com/8301-504083_162-20012557-504083.html',
       'http://seattletimes.com/html/localnews/2010385617_webmansought29.html',
       'http://www.npr.org/templates/story/story.php?storyId=120313570',
       'http://www.nytimes.com/2009/04/12/nyregion/12binghamton.html?pagewanted=all&_r=1&',
       'http://www.wral.com/news/local/story/9845639/',
       'http://www.foxnews.com/story/0,2933,371242,00.html',
       'http://www.cbsnews.com/stories/2008/02/16/national/main3840072.shtml; http://www.esquire.com/news-politics/a4863/steven-kazmierczak-0808/',
       'http://www.stltoday.com/news/local/crime-and-courts/charles-lee-cookie-thornton-behind-the-smile/article_be96f13c-78b9-11df-bfdc-0017a4a78c22.html',
       'http://www.guardian.co.uk/world/2007/dec/06/usa.usgunviolence2',
       'http://www.rivernewsonline.com/main.asp?SectionID=6&SubSectionID=47&ArticleID=368',
       'http://abcnews.go.com/US/story?id=3052278&page=1',
       'http://www.deseretnews.com/article/660205647/Ex-relative-calls-Talovic-vicious-troubled.html?pg=all',
       'http://www.cnn.com/2006/US/10/03/amish.shooting/index.html',
       'http://seattletimes.com/html/localnews/2002898900_huff30m.html',
       'http://www.msnbc.msn.com/id/11167920/ns/us_news-crime_and_courts/t/postal-killer-believed-she-was-target-plot/#.UNyN5cXhe75',
       'http://www.cbsnews.com/stories/2005/03/24/national/main682915.shtml?source=search_story',
       'http://www.cbsnews.com/2100-201_162-679761.html',
       'http://www.cbsnews.com/2100-201_162-659983.html',
       'http://usatoday30.usatoday.com/news/nation/2003-07-08-miss-shooting-main_x.htm',
       'http://articles.chicagotribune.com/2001-02-07/news/0102070122_1_navistar-gun-law-hunting-rifle',
       'http://articles.cnn.com/2002-04-22/justice/ctv.mcdermott.trial_1_michael-mcdermott-jury-deliberates-fate-mental-illness?_s=PM:LAW; http://www.boston.com/news/daily/24/mcdermott_verdict.htm',
       'http://www.sptimes.com/News/123000/news_pf/TampaBay/A_year_later__the_str.shtml',
       'http://archives.starbulletin.com/2000/06/02/news/story2.html',
       'http://www.nytimes.com/1999/09/18/us/death-in-a-church-the-overview-with-question-of-why-unanswered-fort-worth-mourns.html',
       'http://www.independent.co.uk/news/i-dont-plan-to-live-much-longer-just-long-enough-to-kill-the-people-that-greedily-sought-my-destruction-1109610.html',
       'http://www.slate.com/articles/news_and_politics/assessment/2004/04/the_depressive_and_the_psychopath.html',
       'http://articles.cnn.com/2000-01-21/us/kinkel.revisited_1_kip-kinkel-thurston-high-school-oregon-school-shooting?_s=PM:US',
       'http://www.nytimes.com/1998/03/29/us/from-wild-talk-and-friendship-to-five-deaths-in-a-schoolyard.html?sec=&spon=&pagewanted=all',
       'http://www.nytimes.com/2000/04/11/us/hole-in-gun-control-law-lets-mentally-ill-through.html?pagewanted=all&src=pm',
       'http://articles.latimes.com/1997/dec/20/news/mn-431',
       'http://chronicle.augusta.com/stories/1997/09/18/met_214833.shtml',
       'http://articles.sun-sentinel.com/1996-02-11/news/9602110026_1_beach-crew-maintenance-fort-lauderdale',
       'http://web.caller.com/2000/april/03/today/local_ne/4127.html',
       'http://articles.latimes.com/1994-06-22/news/mn-7137_1_air-force',
       'http://www.5280.com/magazine/2008/12/politics-killing?page=0,6',
       'http://www.nytimes.com/1993/12/12/nyregion/tormented-life-special-report-long-slide-privilege-ends-slaughter-train.html',
       'http://news.google.com/newspapers?id=0AhPAAAAIBAJ&sjid=jhUEAAAAIBAJ&pg=6505,2482529&dq=kenneth+junior+french&hl=en',
       'http://articles.latimes.com/1993-07-03/news/mn-10731_1_mortgage-business',
       'http://www.nytimes.com/1992/10/24/nyregion/watkins-glen-killings-called-planned.html',
       'http://www.schoolshooters.info/PL/Subject-Houston_files/Nine%20Brief%20Sketches.pdf',
       'http://www.nytimes.com/1991/11/15/us/ex-postal-worker-kills-3-and-wounds-6-in-michigan.html',
       'http://www.nytimes.com/1991/11/03/us/gunman-in-iowa-wrote-of-plans-in-five-letters.html?pagewanted=all&src=pm',
       'http://www.nytimes.com/1991/10/20/weekinreview/dead-23-texans-and-1-anti-gun-measure.html; http://www.nytimes.com/1991/10/18/us/portrait-of-texas-killer-impatient-and-troubled.html?pagewanted=all&src=pm',
       'http://www.nytimes.com/1990/06/20/us/hazy-records-helped-florida-gunman-buy-arms.html',
       'http://www.nytimes.com/1989/09/16/us/disturbed-past-of-killer-of-7-is-unraveled.html',
       'http://www.recordnet.com/apps/pbcs.dll/article?AID=/20090118/A_NEWS/901170304',
       'http://books.google.com/books?id=JiQUkwBnzgYC&pg=PA44&lpg=PA44&dq=richard+farley+ESL+psychological&source=bl&ots=PqxDlDtznK&sig=K-p8vEN7M2AEdRC0KpxVHjXZN7M&hl=en#v=onepage&q=richard%20farley%20ESL%20psychological&f=false; http://caselaw.findlaw.com/ca-supreme-court/1295931.html',
       '(Supreme Court of Florida Document) http://www.murderpedia.org/male.C/images/cruse_william_b/op-74656.pdf',
       'http://newsok.com/sherrill-feared-mental-illness-rejected/article/2177416',
       'http://www.nctimes.com/news/local/article_2ba4343e-7009-54ce-98df-79a23ff8d0d7.html',
       'http://books.google.com/books?id=Hr3OBwP-lbUC&pg=PA67&lpg=PA67&dq=%22hine+pawnshop%22+gun&source=bl&ots=D55vgfTsnk&sig=zDxr5nohKnNQWvLrUFmZGYQ5ar4&hl=en&sa=X&ei=9WZSUN2FN-XZigKN-oGoCA&ved=0CDcQ6AEwAA#v=onepage&q=%22hine%20pawnshop%22%20gun&f=false',
       'http://news.google.com/newspapers?id=uuYLAAAAIBAJ&sjid=C1kDAAAAIBAJ&pg=4879,1435085&dq=carl+robert+brown'],
      dtype=object)

In [170]:
# 결측값을 investigation needed로 변경

df3['mental_health_sources'] = df3['mental_health_sources'].fillna('investigation needed')

In [171]:
# 결측값 확인

df3[df3['mental_health_sources'].isnull()]['mental_health_sources']

Series([], Name: mental_health_sources, dtype: object)

In [172]:
# 밸류 카운트

df3['mental_health_sources'].value_counts()

investigation needed                                                                                                                51
http://www.sptimes.com/News/123000/news_pf/TampaBay/A_year_later__the_str.shtml                                                      1
http://articles.latimes.com/1997/dec/20/news/mn-431                                                                                  1
http://www.nytimes.com/2000/04/11/us/hole-in-gun-control-law-lets-mentally-ill-through.html?pagewanted=all&src=pm                    1
http://www.nytimes.com/1998/03/29/us/from-wild-talk-and-friendship-to-five-deaths-in-a-schoolyard.html?sec=&spon=&pagewanted=all     1
                                                                                                                                    ..
http://usnews.nbcnews.com/_news/2012/05/30/11959312-six-killed-in-seattle-shootings-including-suspect?lite                           1
http://www.cbsnews.com/8301-201_162-57497820/james-holmes-saw-three-mental-health-professionals-before-shooting/                     1
http://www.jsonline.com/news/milwaukee/friend-of-page-feared-what-he-might-do-426edmg-165668826.html                                 1
http://www.startribune.com/local/171774461.html?refer=y                                                                              1
http://news.google.com/newspapers?id=uuYLAAAAIBAJ&sjid=C1kDAAAAIBAJ&pg=4879,1435085&dq=carl+robert+brown                             1
Name: mental_health_sources, Length: 85, dtype: int64

In [173]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                       0
weapon_type                          0
weapon_details                       0
race                                 0
gender                               0
sources                              0
mental_health_sources                0
sources_additional_age              35
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [174]:
# sources_additional_age 결측치 처리. 11월 20일 심재훈

In [175]:
# 결측값 확인

df3[df3['sources_additional_age'].isnull()]['sources_additional_age']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
29    NaN
30    NaN
31    NaN
32    NaN
33    NaN
34    NaN
Name: sources_additional_age, dtype: object

In [176]:
df3['sources_additional_age'].value_counts()

https://www.chron.com/news/houston-texas/article/Shots-fired-at-Santa-Fe-High-School-12925050.php; https://www.nytimes.com/2018/05/18/us/school-shooting-santa-fe-texas.html; https://www.aol.com/article/news/2018/05/21/suspected-texas-gunman-studied-previous-mass-shootings-report/23439884/                                                                                                                                                                                                                                                           1
http://news.google.com/newspapers?id=c4dIAAAAIBAJ&sjid=_XEDAAAAIBAJ&pg=5163,1527281&dq=jeffrey+weise+mental+ill&hl=en; http://www.cbsnews.com/stories/2005/03/24/national/main682915.shtml?source=search_story; http://www.usnews.com/usnews/news/articles/050404/4redlake.htm; http://www.foxnews.com/story/0,2933,151116,00.html                                                                                                                                                                                                                          1
http://www.usatoday.com/news/nation/2009-04-13-columbine-myths_N.htm; http://www.vpc.org/studies/wgun990420.htm; http://www.slate.com/articles/news_and_politics/assessment/2004/04/the_depressive_and_the_psychopath.html                                                                                                                                                                                                                                                                                                                                  1
http://www.independent.co.uk/news/i-dont-plan-to-live-much-longer-just-long-enough-to-kill-the-people-that-greedily-sought-my-destruction-1109610.html; http://articles.cnn.com/1999-07-30/us/9907_30_atlanta.shooting.06_1_gladys-barton-debra-spivey-barton-note?_s=PM:US; http://www.vpc.org/studies/wgun990729.htm                                                                                                                                                                                                                                      1
http://www.nytimes.com/1999/09/20/us/fort-worth-remembers-those-killed-at-church.html?pagewanted=all&src=pm; http://www.nytimes.com/1999/09/18/us/death-in-a-church-the-overview-with-question-of-why-unanswered-fort-worth-mourns.html; http://www.vpc.org/studies/wgun990915.htm                                                                                                                                                                                                                                                                          1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
http://www.sbsheriff.us/documents/ISLAVISTAINVESTIGATIVESUMMARY.pdf Also: http://www.cnn.com/2014/05/24/us/santa-barbara-isla-vista-shooting-profile/ and http://www.cnn.com/2014/05/24/justice/california-shooting-deaths/index.html and http://www.independent.com/news/2015/feb/20/elliot-rodger-report-details-long-struggle-mental-/ and http://www.cbsnews.com/videos/how-was-elliot-rodger-able-to-purchase-weapons/ and http://www.dailymail.co.uk/news/article-2638922/Santa-Barbara-rampage-killer-bought-three-handguns-legally-gun-shop.html    1
http://www.seattletimes.com/seattle-news/fourth-marysville-shooting-victim-dies-as-another-is-laid-to-rest/ http://www.mercurynews.com/crime-courts/ci_26814211/jaylen-fryberg-included-tributes-washington-school-shooting-victims                                                                                                                                                                                                                                                                                                                         1
http://fox6now.com/2015/06/11/released-menasha-police-issue-final-report-on-trestle-trail-bridge-shooting/ and http://www.postcrescent.com/story/news/local/2015/06/11/police-gunman-prior-suicidal-homicidal-thoughts/71064874/ and http://fox6now.com/2015/05/05/he-was-my-future-husband-fiancee-of-menasha-gunman-says-shes-devastated-for-victims-families/                                                                                                                                                                                            1
http://www.motherjones.com/politics/2015/06/dylann-roofs-attorney; http://www.newsweek.com/report-nine-shot-charleston-south-carolina-church-shooting-344235; http://www.cnn.com/2015/06/19/us/charleston-church-shooting-suspect/; http://www.motherjones.com/politics/2015/06/9-people-dead-mass-shooting-south-carolina-church; http://www.nbcnews.com/storyline/charleston-church-shooting/fbi-says-dyann-roof-should-not-have-been-sold-gun-n390056                                                                                                    1
http://www.nytimes.com/1982/08/21/us/gunman-in-miami-kills-8-in-rampage.html; http://www.nytimes.com/1982/08/24/us/no-charges-planned-against-miami-man-who-shot-gunman.html; http://www.nytimes.com/1982/10/14/us/florida-city-rescinds-law-on-buying-guns.html                                                                                                                                                                                                                                                                                            1
Name: sources_additional_age, Length: 100, dtype: int64

In [177]:
# 결측값을 investigation needed로 변경

df3['sources_additional_age'] = df3['sources_additional_age'].fillna('investigation needed')

In [178]:
# 결측값 확인

df3[df3['sources_additional_age'].isnull()]['sources_additional_age']

Series([], Name: sources_additional_age, dtype: object)

In [179]:
df3.isnull().sum()

case                                 0
location                             0
state                                0
date                                 0
summary                              0
fatalities                           0
injured                              0
total_victims                        0
location.1                           0
age_of_shooter                       0
prior_signs_mental_health_issues     0
mental_health_details                0
weapons_obtained_legally             0
where_obtained                       0
weapon_type                          0
weapon_details                       0
race                                 0
gender                               0
sources                              0
mental_health_sources                0
sources_additional_age               0
latitude                             0
longitude                            0
type                                 0
year                                 0
numweapons                           0
assault                             64
dt                                   0
numsearchresult                      0
dtype: int64

In [180]:
# sources_additional_age 결측치 처리. 11월 20일 심재훈

In [181]:
# 결측치 확인

df3[df3['assault'].isnull()]['assault']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
     ...
59    NaN
60    NaN
63    NaN
65    NaN
66    NaN
Name: assault, Length: 64, dtype: object

In [182]:
# 밸류 카운트

df3['assault'].value_counts()

No     55
Yes    16
Name: assault, dtype: int64

In [183]:
# 확인되지 않음으로 분류함.

df3['assault'] = df3['assault'].fillna('not confirmed')

In [184]:
# 결측치 확인

df3[df3['assault'].isnull()]['assault']

Series([], Name: assault, dtype: object)

In [185]:
df3.isnull().sum()

case                                0
location                            0
state                               0
date                                0
summary                             0
fatalities                          0
injured                             0
total_victims                       0
location.1                          0
age_of_shooter                      0
prior_signs_mental_health_issues    0
mental_health_details               0
weapons_obtained_legally            0
where_obtained                      0
weapon_type                         0
weapon_details                      0
race                                0
gender                              0
sources                             0
mental_health_sources               0
sources_additional_age              0
latitude                            0
longitude                           0
type                                0
year                                0
numweapons                          0
assault                             0
dt                                  0
numsearchresult                     0
dtype: int64

In [186]:
# 범인 자살여부 컬럼 추가 (summary 컬럼에서 추출). 11월 21일 최해정

In [187]:
df3['suicided'] = df3['summary'].str.contains('suicide')

In [188]:
df3.loc[df3['suicided']==True, 'suicided'] = 'Yes'
df3.loc[df3['suicided']==False, 'suicided'] = 'No'

In [189]:
# location.1 컬럼 정제. 11월 21일 최해정

In [190]:
# 유니크 값 확인

df3['location.1'].unique()

array(['School', 'Other', 'workplace', 'religious', 'Religious',
       'Workplace', 'Military', 'Airport', '\nWorkplace', 'Other\n'],
      dtype=object)

In [191]:
# 기존의 값들을 통일시켜줄 함수작성

def space(space) :
    space_dict = {'Other':'Other',
                    'Other\n':'Other',
                    'Workplace':'Workplace',
                    'workplace':'Workplace',
                    '\nWorkplace':'Workplace',
                    'School':'School',
                    'Religious':'Religious',
                    'religious':'Religious',
                    'Military':'Military',
                    'Airport':'Airport',
                   }
    return space_dict.get(space)

In [192]:
# 컬럼에 함수적용

df3['location.1'] = df3['location.1'].apply(space)

In [193]:
# 밸류카운트로 내용 전처리 확인

df3['location.1'].value_counts()

Other        51
Workplace    49
School       20
Religious     8
Military      6
Airport       1
Name: location.1, dtype: int64

In [194]:
# state 컬럼 정제. 11월 21일 최해정

In [195]:
# state 밸류 카운트 확인
# Washington - D.C.처럼 일치하지 않는 값 확인

df3['state'].value_counts()

 California        23
 Florida           12
 Texas             12
 Washington         7
 Colorado           7
 Wisconsin          5
 Pennsylvania       5
 Illinois           5
 New York           5
 Ohio               4
 Maryland           4
 Virginia           3
 Michigan           3
 Georgia            3
 Connecticut        3
 North Carolina     3
 South Carolina     2
 Oregon             2
 Minnesota          2
 Kentucky           2
 Tennessee          2
 Nevada             2
 Missouri           2
 Oklahoma           2
 Indiana            2
 Nebraska           1
 Arkansas           1
 Hawaii             1
 Massachusetts      1
 Mississippi        1
 Utah               1
 Arizona            1
 Lousiana           1
 Alabama            1
 D.C.               1
 New Jersey         1
 Kansas             1
 Iowa               1
Name: state, dtype: int64

In [196]:
# state 명칭 정확성 확인

In [197]:
# 미국 state 명칭 정리된 state_demographics 파일 불러오기

In [198]:
state_list = pd.read_csv('data/state_demographics.csv')['State']

In [199]:
state_list = state_list.unique()

In [200]:
len(state_list)

51

In [201]:
state_list

array(['Connecticut', 'Delaware', 'District of Columbia', 'Florida',
       'Georgia', 'Hawaii', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Louisiana', 'Maine', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'Idaho', 'Illinois',
       'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Oklahoma', 'Oregon',
       'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'Mississippi', 'Missouri', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [202]:
# state 유니크값 확인

In [203]:
df3['state'].unique()

array([' Virginia', ' North Carolina', ' Indiana', ' Illinois',
       ' Alabama', ' Maryland', ' Oklahoma', ' Texas', ' New York',
       ' California', ' Michigan', ' Colorado', ' Georgia', ' Missouri',
       ' Wisconsin', ' New Jersey', ' Florida', ' Ohio', ' Pennsylvania',
       ' Tennessee', ' Nevada', ' Washington', ' Lousiana', ' Kansas',
       ' Oregon', ' South Carolina', ' D.C.', ' Connecticut',
       ' Minnesota', ' Arizona', ' Kentucky', ' Nebraska', ' Utah',
       ' Mississippi', ' Massachusetts', ' Hawaii', ' Arkansas', ' Iowa'],
      dtype=object)

In [204]:
# 좌측 공백 제거

In [205]:
df3['state']= df3['state'].str.lstrip()

In [206]:
# 유니크값이 state_list와 일치하는지 확인

In [207]:
for i in range(len(df3)):
    if df3['state'][i] not in state_list:
        print(df3.loc[i, ['state']])

state    Lousiana
Name: 52, dtype: object
state    D.C.
Name: 68, dtype: object

In [208]:
# 오타값 수정하여 저장

In [209]:
df3.loc[(df3['state'] == 'Lousiana'), 'state'] = 'Louisiana'
df3.loc[(df3['state'] == 'D.C.'), 'state'] = 'Washington'

In [210]:
# 주(state)명 확인

df3['state'].unique()

array(['Virginia', 'North Carolina', 'Indiana', 'Illinois', 'Alabama',
       'Maryland', 'Oklahoma', 'Texas', 'New York', 'California',
       'Michigan', 'Colorado', 'Georgia', 'Missouri', 'Wisconsin',
       'New Jersey', 'Florida', 'Ohio', 'Pennsylvania', 'Tennessee',
       'Nevada', 'Washington', 'Louisiana', 'Kansas', 'Oregon',
       'South Carolina', 'Connecticut', 'Minnesota', 'Arizona',
       'Kentucky', 'Nebraska', 'Utah', 'Mississippi', 'Massachusetts',
       'Hawaii', 'Arkansas', 'Iowa'], dtype=object)

In [211]:
def find_group(value):
    groups = [10, 20, 30, 40, 50, 60, 70, 80]
    for i in range(len(groups)):
        if value+1 <= groups[i]:
            if i == 0:
                return 0
            
            return groups[i-1]

In [212]:
# groupby용 태그 컬럼 추가
df3['age_group'] = [find_group(e) for e in df3['age_of_shooter']]

In [213]:
regulate = pd.read_csv('data/csvData.csv')

In [214]:
set_state_ori = set([state for state in df3['state']])
set_state_alp = set([state for state in regulate['state']])
set_state_ori-set_state_alp

set()

In [215]:
df3=pd.merge(df3, regulate , on='state', how='left')
df3=df3.fillna('no')

In [216]:
df3.columns

Index(['case', 'location', 'state', 'date', 'summary', 'fatalities', 'injured',
       'total_victims', 'location.1', 'age_of_shooter',
       'prior_signs_mental_health_issues', 'mental_health_details',
       'weapons_obtained_legally', 'where_obtained', 'weapon_type',
       'weapon_details', 'race', 'gender', 'sources', 'mental_health_sources',
       'sources_additional_age', 'latitude', 'longitude', 'type', 'year',
       'numweapons', 'assault', 'dt', 'numsearchresult', 'suicided',
       'age_group', 'firearmRegRequired', 'permitReqToCarry',
       'permitReqToPurchase', 'openCarryLegal'],
      dtype='object')

In [217]:
# 공통 전처리 데이터 저장 -> 이후 load_csv로 sgh 코딩
df3.to_csv("data/df3.csv")

In [218]:
# df3.to_csv(r"C:\Users\freef\Desktop\homework\df3.csv")