In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data_puri.csv")
df

,Q,A,label
0,12시 땡!,하루가 또 가네요.,0
1,1지망 학교 떨어졌어,위로해 드립니다.,0
2,3박4일 놀러가고 싶다,여행은 언제나 좋죠.,0
3,3박4일 정도 놀러가고 싶다,여행은 언제나 좋죠.,0
4,PPL 심하네,눈살이 찌푸려지죠.,0
...,...,...,...
14603,히포에스테스의 겨울최저온도 알려 주세요.,겨울최저온도는 13℃ 이상,6
14604,히포에스테스의 습도 알려 주세요.,습도는 40 에서 70%,6
14605,히포에스테스의 비료 알려 주세요.,비료는 보통 요구함,6
14606,히포에스테스의 물주기 알려 주세요.,"물주기 봄은 흙을 촉촉하게 유지함(물에 잠기지 않도록 주의) ,여름은 흙을 촉촉하게...",6
14607,히포에스테스의 병충해 알려 주세요.,"병충해는 온실가루이, 개각충, 진딧물",6

In [6]:
df_label_0 = df[df['label'] == 0]

                    Q            A  label
0              12시 땡!   하루가 또 가네요.      0
1         1지망 학교 떨어졌어    위로해 드립니다.      0
2        3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3     3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4             PPL 심하네   눈살이 찌푸려지죠.      0
...               ...          ...    ...
5285             힘내야지       응원합니다!      0
5286      힘든 것 좀 끝났으면   다 지나갈 거예요.      0
5287     힘든 시기가 지나갔으면   다 지나갈 거예요.      0
5288   힘든 데도 날 도와준 사람  잊지말고 보답하세요.      0
5289           힘차게 시작       응원합니다!      0

[5290 rows x 3 columns]

In [8]:
df_label_0

                    Q            A  label
0              12시 땡!   하루가 또 가네요.      1
1         1지망 학교 떨어졌어    위로해 드립니다.      1
2        3박4일 놀러가고 싶다  여행은 언제나 좋죠.      1
3     3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      1
4             PPL 심하네   눈살이 찌푸려지죠.      1
...               ...          ...    ...
5285             힘내야지       응원합니다!      1
5286      힘든 것 좀 끝났으면   다 지나갈 거예요.      1
5287     힘든 시기가 지나갔으면   다 지나갈 거예요.      1
5288   힘든 데도 날 도와준 사람  잊지말고 보답하세요.      1
5289           힘차게 시작       응원합니다!      1

[5290 rows x 3 columns]

In [9]:
df_label_2 = df[df['label'] == 2]
df_label_2

                              Q                         A  label
8821         짝사랑만큼 고통스러운 건 없겠지.  짝사랑 만큼 감정소모가 큰 건 없을 거예요.      2
8822        1년 넘게 만났는데 지금도 불타올라         정열적인 사랑을 하고 있나봐요.      2
8823            1년 동거 중인데 계속 좋아    서로 깊게 알게되면서 더 좋아졌나봅니다.      2
8824               1년 동거하고 결혼했어                    축하합니다!      2
8825   1년 만났는데도 그 사람에 대해 잘 모르겠어                  더 만나보세요.      2
...                         ...                       ...    ...
11779            훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      2
11780            훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요.      2
11781               흑기사 해주는 짝남.                    설렜겠어요.      2
11782   힘든 연애 좋은 연애라는게 무슨 차이일까?  잘 헤어질 수 있는 사이 여부인 거 같아요.      2
11783                힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요.      2

[2963 rows x 3 columns]

In [10]:
df_label_2['label'] = 1
df_label_2

C:\Users\user\AppData\Local\Temp\ipykernel_5224\2457799785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_label_2['label'] = 1

                              Q                         A  label
8821         짝사랑만큼 고통스러운 건 없겠지.  짝사랑 만큼 감정소모가 큰 건 없을 거예요.      1
8822        1년 넘게 만났는데 지금도 불타올라         정열적인 사랑을 하고 있나봐요.      1
8823            1년 동거 중인데 계속 좋아    서로 깊게 알게되면서 더 좋아졌나봅니다.      1
8824               1년 동거하고 결혼했어                    축하합니다!      1
8825   1년 만났는데도 그 사람에 대해 잘 모르겠어                  더 만나보세요.      1
...                         ...                       ...    ...
11779            훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      1
11780            훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요.      1
11781               흑기사 해주는 짝남.                    설렜겠어요.      1
11782   힘든 연애 좋은 연애라는게 무슨 차이일까?  잘 헤어질 수 있는 사이 여부인 거 같아요.      1
11783                힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요.      1

[2963 rows x 3 columns]

In [11]:
df_label_1 = df[df['label'] == 1]
df_label_1

                         Q                          A  label
5290     1000일 만난 여자친구와 이별         더 오래 만날 사람 만날 거예요.      1
5291       10년 연애. 헤어졌습니다.              더 공허함이 크시겠네요.      1
5292  10년 연애사 되돌아보니 다 부질없네           더 좋은 사람 만나실 거예요.      1
5293              10년 연예의끝               더 마음이 허하겠어요.      1
5294           10년만나다 헤어지네  충분히 슬퍼하고 충분히 아파하다가 이겨내세요.      1
...                    ...                        ...    ...
8816                 힘듭니다.    어떤 말도 위로가 되지 않겠지만 힘내세요.      1
8817          힘이 될런지 모르겠지만    어떤 말도 위로가 되지 않겠지만 힘내세요.      1
8818                 힘이 드네    어떤 말도 위로가 되지 않겠지만 힘내세요.      1
8819                 힘이 없어                      힘내세요!      1
8820           힘이드네.여자들이란.    어떤 말도 위로가 되지 않겠지만 힘내세요.      1

[3531 rows x 3 columns]

In [14]:
df_label_123 = pd.concat([df_label_0, df_label_1, df_label_2 ])
df_label_123

                             Q                         A  label
0                       12시 땡!                하루가 또 가네요.      1
1                  1지망 학교 떨어졌어                 위로해 드립니다.      1
2                 3박4일 놀러가고 싶다               여행은 언제나 좋죠.      1
3              3박4일 정도 놀러가고 싶다               여행은 언제나 좋죠.      1
4                      PPL 심하네                눈살이 찌푸려지죠.      1
...                        ...                       ...    ...
11779           훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      1
11780           훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요.      1
11781              흑기사 해주는 짝남.                    설렜겠어요.      1
11782  힘든 연애 좋은 연애라는게 무슨 차이일까?  잘 헤어질 수 있는 사이 여부인 거 같아요.      1
11783               힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요.      1

[11784 rows x 3 columns]

In [41]:
df_label_3 = df[df['label'] == 3]
df_label_3

,Q,A,label
11784,제 감정이 이상해진 것 같아요. 남편만 보면 화가 치밀어 오르고 감정 조절이 안되요.,감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.,3
11785,더 이상 내 감정을 내가 컨트롤 못 하겠어.,저도 그 기분 이해해요. 많이 힘드시죠?,3
11786,평소 다른 일을 할 때도 비슷해요. 생각한대로 안되면 화가 나고…그런 상황이 지속되...,화가 폭발할 것 같을 때는 그 자리를 피하는 것도 좋은 방법이라고 생각해요.,3
11787,예전보다 화내는 게 과격해진 거 같아.,정말 힘드시겠어요. 화는 남에게도 스스로에게도 상처를 주잖아요.,3
11788,화가 안 참아져.,화가 너무 많이 날 때는 심호흡을 해보는 게 어떨까요? 씁- 후-,3
...,...,...,...
12594,이 병원 저 병원 다 가봤는데 시원한 소리를 하나도 못 들었어.,좋은 일이네요. 후에 다시 증상이 발생하면 꼭 병원을 찾아 주세요.,3
12595,파편이 튀어서 그 때 저도 응급실 가서 치료 받기도 했고…,응급실에 가셨다니 정말 놀랐어요. 아무 문제 없으신가요? 걱정 되네요.,3
12596,지금 상태가 너무 안 좋아서 학교 안 나가고 있어요.,상태가 더 안 좋아지셨군요. 걱정이 되네요.,3
12597,진짜 심해진 거 같긴 해요.,정말 힘드시겠어요. 지금도 증상이 심하신가요?,3
12598,그런데 증상이 나빠진 거 같아.,너무 심하시면 병원을 다시 가보는 건 어떨까요?,3

In [42]:
df_label_4 = df[df['label'] == 4]
df_label_4

,Q,A,label
12599,진짜 잘자라는 우리 애기,우와 되게 잘 크네요 저희집 애는 너무 가녀린데,4
12600,얼렁 활짝 폈으면 좋겠어요,잎이 완전 크네요 대박,4
12601,새순이 잘 나고 있어요,완전 새순파티네요 굿굿,4
12602,빛나는 잎파리들이 너무 예뻐서 기분도 좋아지는 것 같아요,식물들 햇볕샤워 시간이 제일 예뻐보이는 시간이죠 초록이들 빛반사되어서 예뻐요,4
12603,세잎이 나오고 있어요,크 완전 기운차게 나네요,4
12604,예쁜 화분으로 옮겨주었어요 웃지랄수록 이뻐지겠죠,어쩜 센스 넘치시네요 너무 이뻐요,4
12605,재미져요 식물놀이,너무 예뻐요,4
12606,폭풍성장햐주고 있어서 너무 고마운 친구에요,알맞은 환경에 적응했나 봅니다 예뻐요,4
12607,꽃대가 하나 올라왔어요 너무 귀여워요,너무 기특하고 예쁘네요,4
12608,드디어 튤립 한송이가 피었어요,너무 아름다워요 봄의여왕 같이 도도하고 우아합니다,4
12609,꽃이 피고 있어요,봄이 왓네요 예쁘게 피어라,4
12610,까만 잎이 점점 커지는 중이에요,우와~~ 넘 멋진데요..,4
12611,점점 멋진 무늬 잎이 나오고있어요,빨리 빨리 자라서 대품 되거랏!!!얍,4
12612,꽃봉오리가 펼쳐지고있어요,멋진 꽃이네요,4
12613,무늬 진짜 잘나왔습니다,발색이 잘 되었네요.,4
12614,매일 돌봐줄때보다 더 잘자란 너낌이에용,넘 예쁘네요? 침 닦고 갑니당ㅎㅎ,4
12615,봄이니까 꽃이 마구 땡겨서 사고있어요,꽃 넘 예쁘네요 역시 봄은 꽃이쥬,4
12616,모퉁이 장식장위에서 식물등 혼자 받으면서 조용히 은은하게 폼새를 뽐내고 있네요,넘 고혹적이에요~,4
12617,요즘 쑥쑥자라서 이뻐보여요,역시 멋진아이네요,4
12618,물꽃이로 키우고있는데 봄이니 예뻐보여요,미모 인정입니다,4
12619,잘 자라줬으면 좋겠네요,사랑스러운 녀석들건강하게 잘 자라라,4

In [43]:
df_label_5 = df[df['label'] == 5]
df_label_5

,Q,A,label
12620,식물 처음 키워보는데 어떤 식물이 좋을까?,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12621,키우기 좋은 식물 추천해줘,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12622,초보자에게 좋은 식물 추천해줘,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12623,초보자가 키우기 좋은 식물은 뭐야?,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12624,처음 키우는 식물 추천해줘,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12625,처음 키우는 식물은 어떤게 좋아?,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12626,식물 키워보고 싶은데 추천해줘.,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12627,식물 어떤거 키우는게 좋을까?,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12628,식물 키워보기 전에 알아보고 싶어.,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5
12629,화분 어떤거 키우는게 좋을까?,화면 상단에 보시면 식물 추천이 있어요. 항목을 입력하시면 가장 항목에 맞는 식물을...,5

In [51]:
df_label_6 = df[df['label'] == 6]
df_label_6

,Q,A,label
12630,가울테리아의 관리요구도 알려 주세요.,관리요구도는 낮음 (잘 견딤),6
12631,가울테리아의 광요구도 알려 주세요.,"광요구도는 중간 광도(800에서 1,500 Lux),높은 광도(1,500에서 10,...",6
12632,가울테리아의 배치장소 알려 주세요.,"배치장소는 거실 창측 (실내깊이 150에서 300cm),발코니 내측 (실내깊이 50...",6
12633,가울테리아의 생장속도 알려 주세요.,생장속도는 느림,6
12634,가울테리아의 생육적온 알려 주세요.,생육적온은 16에서 20℃,6
...,...,...,...
14603,히포에스테스의 겨울최저온도 알려 주세요.,겨울최저온도는 13℃ 이상,6
14604,히포에스테스의 습도 알려 주세요.,습도는 40 에서 70%,6
14605,히포에스테스의 비료 알려 주세요.,비료는 보통 요구함,6
14606,히포에스테스의 물주기 알려 주세요.,"물주기 봄은 흙을 촉촉하게 유지함(물에 잠기지 않도록 주의) ,여름은 흙을 촉촉하게...",6
14607,히포에스테스의 병충해 알려 주세요.,"병충해는 온실가루이, 개각충, 진딧물",6

In [45]:
df_label_3['label'] = 2

C:\Users\user\AppData\Local\Temp\ipykernel_5224\2837145871.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_label_3['label'] = 2

In [46]:
df_label_4['label'] = 3

C:\Users\user\AppData\Local\Temp\ipykernel_5224\1808484775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_label_4['label'] = 3

In [47]:
df_label_5['label'] = 4

C:\Users\user\AppData\Local\Temp\ipykernel_5224\1772475017.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_label_5['label'] = 4

In [52]:
df_label_6['label'] = 5

C:\Users\user\AppData\Local\Temp\ipykernel_5224\2300735479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_label_6['label'] = 5

In [53]:
df_label_3

,Q,A,label
11784,제 감정이 이상해진 것 같아요. 남편만 보면 화가 치밀어 오르고 감정 조절이 안되요.,감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.,2
11785,더 이상 내 감정을 내가 컨트롤 못 하겠어.,저도 그 기분 이해해요. 많이 힘드시죠?,2
11786,평소 다른 일을 할 때도 비슷해요. 생각한대로 안되면 화가 나고…그런 상황이 지속되...,화가 폭발할 것 같을 때는 그 자리를 피하는 것도 좋은 방법이라고 생각해요.,2
11787,예전보다 화내는 게 과격해진 거 같아.,정말 힘드시겠어요. 화는 남에게도 스스로에게도 상처를 주잖아요.,2
11788,화가 안 참아져.,화가 너무 많이 날 때는 심호흡을 해보는 게 어떨까요? 씁- 후-,2
...,...,...,...
12594,이 병원 저 병원 다 가봤는데 시원한 소리를 하나도 못 들었어.,좋은 일이네요. 후에 다시 증상이 발생하면 꼭 병원을 찾아 주세요.,2
12595,파편이 튀어서 그 때 저도 응급실 가서 치료 받기도 했고…,응급실에 가셨다니 정말 놀랐어요. 아무 문제 없으신가요? 걱정 되네요.,2
12596,지금 상태가 너무 안 좋아서 학교 안 나가고 있어요.,상태가 더 안 좋아지셨군요. 걱정이 되네요.,2
12597,진짜 심해진 거 같긴 해요.,정말 힘드시겠어요. 지금도 증상이 심하신가요?,2
12598,그런데 증상이 나빠진 거 같아.,너무 심하시면 병원을 다시 가보는 건 어떨까요?,2

In [54]:
df_puri = pd.concat([df_label_123, df_label_3, df_label_4, df_label_5, df_label_6])
df_puri

,Q,A,label
0,12시 땡!,하루가 또 가네요.,1
1,1지망 학교 떨어졌어,위로해 드립니다.,1
2,3박4일 놀러가고 싶다,여행은 언제나 좋죠.,1
3,3박4일 정도 놀러가고 싶다,여행은 언제나 좋죠.,1
4,PPL 심하네,눈살이 찌푸려지죠.,1
...,...,...,...
14603,히포에스테스의 겨울최저온도 알려 주세요.,겨울최저온도는 13℃ 이상,5
14604,히포에스테스의 습도 알려 주세요.,습도는 40 에서 70%,5
14605,히포에스테스의 비료 알려 주세요.,비료는 보통 요구함,5
14606,히포에스테스의 물주기 알려 주세요.,"물주기 봄은 흙을 촉촉하게 유지함(물에 잠기지 않도록 주의) ,여름은 흙을 촉촉하게...",5
14607,히포에스테스의 병충해 알려 주세요.,"병충해는 온실가루이, 개각충, 진딧물",5

In [55]:
df_puri.to_csv("plant_puri_label.csv")

In [56]:
df_puri.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14608 entries, 0 to 14607
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q       14608 non-null  object
 1   A       14608 non-null  object
 2   label   14608 non-null  int64
dtypes: int64(1), object(2)
memory usage: 456.5+ KB