In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/done/apple.csv', encoding='cp949')
temp = pd.read_csv('data/done/temp.csv', encoding='cp949')
sun = pd.read_csv('data/done/sun.csv', encoding='cp949')
humidity = pd.read_csv('data/done/humidity.csv', encoding='cp949')
wind = pd.read_csv('data/done/wind_all.csv', encoding='cp949')
pressure = pd.read_csv('data/done/pressure.csv', encoding='cp949')

In [3]:
season_temp = temp.copy()
season_temp['계절'] = season_temp['월'].replace([3,4,5,6,7,8,9], ['봄','봄','여름','여름','여름','가을','가을'])
season_temp.drop(columns='월', inplace=True)

season_temp = round(season_temp.groupby(['년', '계절', '지역']).mean(), 1).reset_index()

spring_temp = season_temp[season_temp['계절'] == '봄'].drop(columns='계절')
spring_temp.columns = ['년', '지역', 'sp평균기온(℃)', 'sp최고기온 평균(℃)', 'sp최저기온 평균(℃)', 'sp강수량(mm)']

summer_temp = season_temp[season_temp['계절'] == '여름'].drop(columns='계절')
summer_temp.columns = ['년', '지역', 'su평균기온(℃)', 'su최고기온 평균(℃)', 'su최저기온 평균(℃)', 'su강수량(mm)']

fall_temp = season_temp[season_temp['계절'] == '가을'].drop(columns='계절')
fall_temp.columns = ['년', '지역', 'fa평균기온(℃)', 'fa최고기온 평균(℃)', 'fa최저기온 평균(℃)', 'fa강수량(mm)']

In [4]:
weathers = [temp, sun, humidity, wind, pressure]
seasons = [spring_temp, summer_temp, fall_temp]
data = df.copy()

In [5]:
for idx, weather in enumerate(weathers):
    tmp = round(weather.groupby(['년', '지역']).mean(), 1).drop(columns='월').reset_index()
    data = data.merge(tmp, on=['년', '지역'])

In [6]:
for season in seasons:
    data = data.merge(season, on=['년', '지역'])

In [7]:
data.sample(5)

,년,지역,면적 (ha),10a당 생산량 (kg),생산량 (톤),평균기온(℃),최고기온 평균(℃),최저기온 평균(℃),강수량(mm),합계일조시간(hr),...,sp최저기온 평균(℃),sp강수량(mm),su평균기온(℃),su최고기온 평균(℃),su최저기온 평균(℃),su강수량(mm),fa평균기온(℃),fa최고기온 평균(℃),fa최저기온 평균(℃),fa강수량(mm)
572,2017,충청남도,1584,2050,29362,18.4,24.3,13.2,755.7,235.8,...,2.6,206.0,21.8,27.5,16.8,949.1,22.6,27.8,18.2,1015.2
499,2013,대구광역시,86,1378,1185,21.1,26.8,16.3,114.0,233.4,...,4.9,57.8,24.4,29.9,20.0,127.6,26.0,31.2,22.0,149.8
392,2006,인천광역시,1,0,0,16.6,20.9,13.2,406.9,201.5,...,2.8,75.4,19.0,23.1,15.9,842.9,23.0,27.4,19.6,84.4
82,1986,경상남도,1194,1105,13194,18.3,23.7,13.6,1478.8,239.8,...,4.0,623.2,20.8,25.7,16.6,1991.9,22.8,28.0,18.6,1564.6
586,2018,전라북도,2643,1082,28597,19.4,25.3,14.4,1657.2,235.3,...,4.4,1152.1,22.3,28.1,17.5,1459.5,24.0,29.4,19.6,2459.0

In [8]:
data.to_csv('data/done/final.csv', encoding='cp949', index=False)